<?php
/**
 * SAMSCompetitionsAPIApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SAMS REST API v2
 *
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SAMSCompetitionsAPIApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SAMSCompetitionsAPIApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAllCompetitions
     *
     * Returns all available competitions as a paged list..
     *
     */
    public function testGetAllCompetitions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCompetitionByUuid
     *
     * Returns a competition identified by the given UUID.
     *
     */
    public function testGetCompetitionByUuid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMatchGroupsForCompetition
     *
     * Returns all match groups corresponding to the competition identified by the given UUID.
     *
     */
    public function testGetMatchGroupsForCompetition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRankingsForCompetition
     *
     * Returns the rankings of a competition identified by the given UUID..
     *
     */
    public function testGetRankingsForCompetition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTeamsForCompetition
     *
     * Returns all teams of a competition identified by the given UUID as a paged list..
     *
     */
    public function testGetTeamsForCompetition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
