<?php
/**
 * SAMSMatchDaysAPIApi
 * PHP version 8.1
 *
 * @category Class
 * @package  SAMSPlugin\RestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SAMS REST API v2
 *
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SAMSPlugin\RestClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use SAMSPlugin\RestClient\ApiException;
use SAMSPlugin\RestClient\Configuration;
use SAMSPlugin\RestClient\FormDataProcessor;
use SAMSPlugin\RestClient\HeaderSelector;
use SAMSPlugin\RestClient\ObjectSerializer;

/**
 * SAMSMatchDaysAPIApi Class Doc Comment
 *
 * @category Class
 * @package  SAMSPlugin\RestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SAMSMatchDaysAPIApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getAllMatchDays' => [
            'application/json',
        ],
        'getMatchDayByUuid' => [
            'application/json',
        ],
        'getMatchesByMatchDay' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getAllMatchDays
     *
     * Returns all available match days as a paged list.
     *
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string|null $association Filter for association using the given UUID. Defaults to no filtering. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllMatchDays'] to see the possible values for this operation
     *
     * @throws \SAMSPlugin\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SAMSPlugin\RestClient\Model\ValidationError|\SAMSPlugin\RestClient\Model\ResponseExceptionMessage|\SAMSPlugin\RestClient\Model\ResponseExceptionMessage|\SAMSPlugin\RestClient\Model\ResponseException|\SAMSPlugin\RestClient\Model\LeagueMatchDayPage
     */
    public function getAllMatchDays($x_api_key = null, $page = null, $size = null, $association = null, string $contentType = self::contentTypes['getAllMatchDays'][0])
    {
        list($response) = $this->getAllMatchDaysWithHttpInfo($x_api_key, $page, $size, $association, $contentType);
        return $response;
    }

    /**
     * Operation getAllMatchDaysWithHttpInfo
     *
     * Returns all available match days as a paged list.
     *
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string|null $association Filter for association using the given UUID. Defaults to no filtering. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllMatchDays'] to see the possible values for this operation
     *
     * @throws \SAMSPlugin\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SAMSPlugin\RestClient\Model\ValidationError|\SAMSPlugin\RestClient\Model\ResponseExceptionMessage|\SAMSPlugin\RestClient\Model\ResponseExceptionMessage|\SAMSPlugin\RestClient\Model\ResponseException|\SAMSPlugin\RestClient\Model\LeagueMatchDayPage, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllMatchDaysWithHttpInfo($x_api_key = null, $page = null, $size = null, $association = null, string $contentType = self::contentTypes['getAllMatchDays'][0])
    {
        $request = $this->getAllMatchDaysRequest($x_api_key, $page, $size, $association, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 400:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\ValidationError',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\ResponseException',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\LeagueMatchDayPage',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\SAMSPlugin\RestClient\Model\LeagueMatchDayPage',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\ResponseException',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\LeagueMatchDayPage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAllMatchDaysAsync
     *
     * Returns all available match days as a paged list.
     *
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string|null $association Filter for association using the given UUID. Defaults to no filtering. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllMatchDays'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllMatchDaysAsync($x_api_key = null, $page = null, $size = null, $association = null, string $contentType = self::contentTypes['getAllMatchDays'][0])
    {
        return $this->getAllMatchDaysAsyncWithHttpInfo($x_api_key, $page, $size, $association, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllMatchDaysAsyncWithHttpInfo
     *
     * Returns all available match days as a paged list.
     *
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string|null $association Filter for association using the given UUID. Defaults to no filtering. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllMatchDays'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllMatchDaysAsyncWithHttpInfo($x_api_key = null, $page = null, $size = null, $association = null, string $contentType = self::contentTypes['getAllMatchDays'][0])
    {
        $returnType = '\SAMSPlugin\RestClient\Model\LeagueMatchDayPage';
        $request = $this->getAllMatchDaysRequest($x_api_key, $page, $size, $association, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllMatchDays'
     *
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string|null $association Filter for association using the given UUID. Defaults to no filtering. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllMatchDays'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllMatchDaysRequest($x_api_key = null, $page = null, $size = null, $association = null, string $contentType = self::contentTypes['getAllMatchDays'][0])
    {






        $resourcePath = '/match-days';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $association,
            'association', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_key !== null) {
            $headerParams['X-Api-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/hal+json; charset=UTF-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMatchDayByUuid
     *
     * Returns a match day identified by the given UUID
     *
     * @param  string $uuid uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchDayByUuid'] to see the possible values for this operation
     *
     * @throws \SAMSPlugin\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SAMSPlugin\RestClient\Model\ValidationError|\SAMSPlugin\RestClient\Model\ResponseExceptionMessage|\SAMSPlugin\RestClient\Model\ResponseExceptionMessage|\SAMSPlugin\RestClient\Model\ResponseException|\SAMSPlugin\RestClient\Model\LeagueMatchDayDto
     */
    public function getMatchDayByUuid($uuid, $x_api_key = null, string $contentType = self::contentTypes['getMatchDayByUuid'][0])
    {
        list($response) = $this->getMatchDayByUuidWithHttpInfo($uuid, $x_api_key, $contentType);
        return $response;
    }

    /**
     * Operation getMatchDayByUuidWithHttpInfo
     *
     * Returns a match day identified by the given UUID
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchDayByUuid'] to see the possible values for this operation
     *
     * @throws \SAMSPlugin\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SAMSPlugin\RestClient\Model\ValidationError|\SAMSPlugin\RestClient\Model\ResponseExceptionMessage|\SAMSPlugin\RestClient\Model\ResponseExceptionMessage|\SAMSPlugin\RestClient\Model\ResponseException|\SAMSPlugin\RestClient\Model\LeagueMatchDayDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMatchDayByUuidWithHttpInfo($uuid, $x_api_key = null, string $contentType = self::contentTypes['getMatchDayByUuid'][0])
    {
        $request = $this->getMatchDayByUuidRequest($uuid, $x_api_key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 400:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\ValidationError',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\ResponseException',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\LeagueMatchDayDto',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\SAMSPlugin\RestClient\Model\LeagueMatchDayDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\ResponseException',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\LeagueMatchDayDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getMatchDayByUuidAsync
     *
     * Returns a match day identified by the given UUID
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchDayByUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMatchDayByUuidAsync($uuid, $x_api_key = null, string $contentType = self::contentTypes['getMatchDayByUuid'][0])
    {
        return $this->getMatchDayByUuidAsyncWithHttpInfo($uuid, $x_api_key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMatchDayByUuidAsyncWithHttpInfo
     *
     * Returns a match day identified by the given UUID
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchDayByUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMatchDayByUuidAsyncWithHttpInfo($uuid, $x_api_key = null, string $contentType = self::contentTypes['getMatchDayByUuid'][0])
    {
        $returnType = '\SAMSPlugin\RestClient\Model\LeagueMatchDayDto';
        $request = $this->getMatchDayByUuidRequest($uuid, $x_api_key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMatchDayByUuid'
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchDayByUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getMatchDayByUuidRequest($uuid, $x_api_key = null, string $contentType = self::contentTypes['getMatchDayByUuid'][0])
    {

        // verify the required parameter 'uuid' is set
        if ($uuid === null || (is_array($uuid) && count($uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uuid when calling getMatchDayByUuid'
            );
        }



        $resourcePath = '/match-days/{uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_api_key !== null) {
            $headerParams['X-Api-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }

        // path params
        if ($uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'uuid' . '}',
                ObjectSerializer::toPathValue($uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/hal+json; charset=UTF-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMatchesByMatchDay
     *
     * Returns all matches of a match day based on the given UUID. The default page size is 20. The page size must not be greater than 100
     *
     * @param  string $uuid uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchesByMatchDay'] to see the possible values for this operation
     *
     * @throws \SAMSPlugin\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SAMSPlugin\RestClient\Model\ValidationError|\SAMSPlugin\RestClient\Model\ResponseExceptionMessage|\SAMSPlugin\RestClient\Model\ResponseExceptionMessage|\SAMSPlugin\RestClient\Model\ResponseException|\SAMSPlugin\RestClient\Model\LeagueMatchPage
     */
    public function getMatchesByMatchDay($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getMatchesByMatchDay'][0])
    {
        list($response) = $this->getMatchesByMatchDayWithHttpInfo($uuid, $x_api_key, $page, $size, $contentType);
        return $response;
    }

    /**
     * Operation getMatchesByMatchDayWithHttpInfo
     *
     * Returns all matches of a match day based on the given UUID. The default page size is 20. The page size must not be greater than 100
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchesByMatchDay'] to see the possible values for this operation
     *
     * @throws \SAMSPlugin\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SAMSPlugin\RestClient\Model\ValidationError|\SAMSPlugin\RestClient\Model\ResponseExceptionMessage|\SAMSPlugin\RestClient\Model\ResponseExceptionMessage|\SAMSPlugin\RestClient\Model\ResponseException|\SAMSPlugin\RestClient\Model\LeagueMatchPage, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMatchesByMatchDayWithHttpInfo($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getMatchesByMatchDay'][0])
    {
        $request = $this->getMatchesByMatchDayRequest($uuid, $x_api_key, $page, $size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 400:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\ValidationError',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\ResponseException',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\SAMSPlugin\RestClient\Model\LeagueMatchPage',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\SAMSPlugin\RestClient\Model\LeagueMatchPage',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\ResponseException',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMSPlugin\RestClient\Model\LeagueMatchPage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getMatchesByMatchDayAsync
     *
     * Returns all matches of a match day based on the given UUID. The default page size is 20. The page size must not be greater than 100
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchesByMatchDay'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMatchesByMatchDayAsync($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getMatchesByMatchDay'][0])
    {
        return $this->getMatchesByMatchDayAsyncWithHttpInfo($uuid, $x_api_key, $page, $size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMatchesByMatchDayAsyncWithHttpInfo
     *
     * Returns all matches of a match day based on the given UUID. The default page size is 20. The page size must not be greater than 100
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchesByMatchDay'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMatchesByMatchDayAsyncWithHttpInfo($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getMatchesByMatchDay'][0])
    {
        $returnType = '\SAMSPlugin\RestClient\Model\LeagueMatchPage';
        $request = $this->getMatchesByMatchDayRequest($uuid, $x_api_key, $page, $size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMatchesByMatchDay'
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchesByMatchDay'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getMatchesByMatchDayRequest($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getMatchesByMatchDay'][0])
    {

        // verify the required parameter 'uuid' is set
        if ($uuid === null || (is_array($uuid) && count($uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uuid when calling getMatchesByMatchDay'
            );
        }





        $resourcePath = '/match-days/{uuid}/league-matches';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_key !== null) {
            $headerParams['X-Api-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }

        // path params
        if ($uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'uuid' . '}',
                ObjectSerializer::toPathValue($uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/hal+json; charset=UTF-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
