/**
 * SAMS REST API v2
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CommitteeMember from './CommitteeMember';
import LinkDto from './LinkDto';

/**
 * The Committee model module.
 * @module model/Committee
 * @version 2.1
 */
class Committee {
    /**
     * Constructs a new <code>Committee</code>.
     * @alias module:model/Committee
     */
    constructor() { 
        
        Committee.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Committee</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Committee} obj Optional instance to populate.
     * @return {module:model/Committee} The populated <code>Committee</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Committee();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('_links')) {
                obj['_links'] = ApiClient.convertToType(data['_links'], {'String': LinkDto});
            }
            if (data.hasOwnProperty('_embedded')) {
                obj['_embedded'] = ApiClient.convertToType(data['_embedded'], {'String': Object});
            }
            if (data.hasOwnProperty('associationUuid')) {
                obj['associationUuid'] = ApiClient.convertToType(data['associationUuid'], 'String');
            }
            if (data.hasOwnProperty('members')) {
                obj['members'] = ApiClient.convertToType(data['members'], [CommitteeMember]);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('shortname')) {
                obj['shortname'] = ApiClient.convertToType(data['shortname'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('imageLink')) {
                obj['imageLink'] = ApiClient.convertToType(data['imageLink'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Committee</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Committee</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['associationUuid'] && !(typeof data['associationUuid'] === 'string' || data['associationUuid'] instanceof String)) {
            throw new Error("Expected the field `associationUuid` to be a primitive type in the JSON string but got " + data['associationUuid']);
        }
        if (data['members']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['members'])) {
                throw new Error("Expected the field `members` to be an array in the JSON data but got " + data['members']);
            }
            // validate the optional field `members` (array)
            for (const item of data['members']) {
                CommitteeMember.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['shortname'] && !(typeof data['shortname'] === 'string' || data['shortname'] instanceof String)) {
            throw new Error("Expected the field `shortname` to be a primitive type in the JSON string but got " + data['shortname']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['imageLink'] && !(typeof data['imageLink'] === 'string' || data['imageLink'] instanceof String)) {
            throw new Error("Expected the field `imageLink` to be a primitive type in the JSON string but got " + data['imageLink']);
        }

        return true;
    }


}



/**
 * Entity unique identifier
 * @member {String} uuid
 */
Committee.prototype['uuid'] = undefined;

/**
 * @member {Object.<String, module:model/LinkDto>} _links
 */
Committee.prototype['_links'] = undefined;

/**
 * @member {Object.<String, Object>} _embedded
 */
Committee.prototype['_embedded'] = undefined;

/**
 * Reference to the association this entity belongs to
 * @member {String} associationUuid
 */
Committee.prototype['associationUuid'] = undefined;

/**
 * @member {Array.<module:model/CommitteeMember>} members
 */
Committee.prototype['members'] = undefined;

/**
 * @member {String} name
 */
Committee.prototype['name'] = undefined;

/**
 * @member {String} shortname
 */
Committee.prototype['shortname'] = undefined;

/**
 * @member {String} description
 */
Committee.prototype['description'] = undefined;

/**
 * @member {String} type
 */
Committee.prototype['type'] = undefined;

/**
 * @member {String} imageLink
 */
Committee.prototype['imageLink'] = undefined;






export default Committee;

