/**
 * SAMS REST API v2
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LinkDto from './LinkDto';

/**
 * The CompetitionDto model module.
 * @module model/CompetitionDto
 * @version 2.1
 */
class CompetitionDto {
    /**
     * Constructs a new <code>CompetitionDto</code>.
     * @alias module:model/CompetitionDto
     */
    constructor() { 
        
        CompetitionDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompetitionDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompetitionDto} obj Optional instance to populate.
     * @return {module:model/CompetitionDto} The populated <code>CompetitionDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompetitionDto();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('_links')) {
                obj['_links'] = ApiClient.convertToType(data['_links'], {'String': LinkDto});
            }
            if (data.hasOwnProperty('_embedded')) {
                obj['_embedded'] = ApiClient.convertToType(data['_embedded'], {'String': Object});
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('shortName')) {
                obj['shortName'] = ApiClient.convertToType(data['shortName'], 'String');
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
            }
            if (data.hasOwnProperty('leagueHierarchyUuid')) {
                obj['leagueHierarchyUuid'] = ApiClient.convertToType(data['leagueHierarchyUuid'], 'String');
            }
            if (data.hasOwnProperty('seasonUuid')) {
                obj['seasonUuid'] = ApiClient.convertToType(data['seasonUuid'], 'String');
            }
            if (data.hasOwnProperty('associationUuid')) {
                obj['associationUuid'] = ApiClient.convertToType(data['associationUuid'], 'String');
            }
            if (data.hasOwnProperty('latestResultUpdate')) {
                obj['latestResultUpdate'] = ApiClient.convertToType(data['latestResultUpdate'], 'Date');
            }
            if (data.hasOwnProperty('latestStructuralUpdate')) {
                obj['latestStructuralUpdate'] = ApiClient.convertToType(data['latestStructuralUpdate'], 'Date');
            }
            if (data.hasOwnProperty('scoreTableCalculationMode')) {
                obj['scoreTableCalculationMode'] = ApiClient.convertToType(data['scoreTableCalculationMode'], 'String');
            }
            if (data.hasOwnProperty('superCompetitionUuid')) {
                obj['superCompetitionUuid'] = ApiClient.convertToType(data['superCompetitionUuid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CompetitionDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CompetitionDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['shortName'] && !(typeof data['shortName'] === 'string' || data['shortName'] instanceof String)) {
            throw new Error("Expected the field `shortName` to be a primitive type in the JSON string but got " + data['shortName']);
        }
        // ensure the json data is a string
        if (data['gender'] && !(typeof data['gender'] === 'string' || data['gender'] instanceof String)) {
            throw new Error("Expected the field `gender` to be a primitive type in the JSON string but got " + data['gender']);
        }
        // ensure the json data is a string
        if (data['leagueHierarchyUuid'] && !(typeof data['leagueHierarchyUuid'] === 'string' || data['leagueHierarchyUuid'] instanceof String)) {
            throw new Error("Expected the field `leagueHierarchyUuid` to be a primitive type in the JSON string but got " + data['leagueHierarchyUuid']);
        }
        // ensure the json data is a string
        if (data['seasonUuid'] && !(typeof data['seasonUuid'] === 'string' || data['seasonUuid'] instanceof String)) {
            throw new Error("Expected the field `seasonUuid` to be a primitive type in the JSON string but got " + data['seasonUuid']);
        }
        // ensure the json data is a string
        if (data['associationUuid'] && !(typeof data['associationUuid'] === 'string' || data['associationUuid'] instanceof String)) {
            throw new Error("Expected the field `associationUuid` to be a primitive type in the JSON string but got " + data['associationUuid']);
        }
        // ensure the json data is a string
        if (data['scoreTableCalculationMode'] && !(typeof data['scoreTableCalculationMode'] === 'string' || data['scoreTableCalculationMode'] instanceof String)) {
            throw new Error("Expected the field `scoreTableCalculationMode` to be a primitive type in the JSON string but got " + data['scoreTableCalculationMode']);
        }
        // ensure the json data is a string
        if (data['superCompetitionUuid'] && !(typeof data['superCompetitionUuid'] === 'string' || data['superCompetitionUuid'] instanceof String)) {
            throw new Error("Expected the field `superCompetitionUuid` to be a primitive type in the JSON string but got " + data['superCompetitionUuid']);
        }

        return true;
    }


}



/**
 * Entity unique identifier
 * @member {String} uuid
 */
CompetitionDto.prototype['uuid'] = undefined;

/**
 * @member {Object.<String, module:model/LinkDto>} _links
 */
CompetitionDto.prototype['_links'] = undefined;

/**
 * @member {Object.<String, Object>} _embedded
 */
CompetitionDto.prototype['_embedded'] = undefined;

/**
 * @member {String} name
 */
CompetitionDto.prototype['name'] = undefined;

/**
 * @member {String} shortName
 */
CompetitionDto.prototype['shortName'] = undefined;

/**
 * @member {module:model/CompetitionDto.GenderEnum} gender
 */
CompetitionDto.prototype['gender'] = undefined;

/**
 * @member {String} leagueHierarchyUuid
 */
CompetitionDto.prototype['leagueHierarchyUuid'] = undefined;

/**
 * @member {String} seasonUuid
 */
CompetitionDto.prototype['seasonUuid'] = undefined;

/**
 * @member {String} associationUuid
 */
CompetitionDto.prototype['associationUuid'] = undefined;

/**
 * @member {Date} latestResultUpdate
 */
CompetitionDto.prototype['latestResultUpdate'] = undefined;

/**
 * @member {Date} latestStructuralUpdate
 */
CompetitionDto.prototype['latestStructuralUpdate'] = undefined;

/**
 * @member {String} scoreTableCalculationMode
 */
CompetitionDto.prototype['scoreTableCalculationMode'] = undefined;

/**
 * If this competition is the sub-competition of a super competition then this UUID points to this super competition.
 * @member {String} superCompetitionUuid
 */
CompetitionDto.prototype['superCompetitionUuid'] = undefined;





/**
 * Allowed values for the <code>gender</code> property.
 * @enum {String}
 * @readonly
 */
CompetitionDto['GenderEnum'] = {

    /**
     * value: "MALE"
     * @const
     */
    "MALE": "MALE",

    /**
     * value: "FEMALE"
     * @const
     */
    "FEMALE": "FEMALE",

    /**
     * value: "MIXED"
     * @const
     */
    "MIXED": "MIXED"
};



export default CompetitionDto;

