/**
 * SAMS REST API v2
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LeagueRankingsEntryDto from './LeagueRankingsEntryDto';
import LinkDto from './LinkDto';

/**
 * The CompetitionMatchGroupRankingsDto model module.
 * @module model/CompetitionMatchGroupRankingsDto
 * @version 2.1
 */
class CompetitionMatchGroupRankingsDto {
    /**
     * Constructs a new <code>CompetitionMatchGroupRankingsDto</code>.
     * @alias module:model/CompetitionMatchGroupRankingsDto
     */
    constructor() { 
        
        CompetitionMatchGroupRankingsDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompetitionMatchGroupRankingsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompetitionMatchGroupRankingsDto} obj Optional instance to populate.
     * @return {module:model/CompetitionMatchGroupRankingsDto} The populated <code>CompetitionMatchGroupRankingsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompetitionMatchGroupRankingsDto();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('_links')) {
                obj['_links'] = ApiClient.convertToType(data['_links'], {'String': LinkDto});
            }
            if (data.hasOwnProperty('_embedded')) {
                obj['_embedded'] = ApiClient.convertToType(data['_embedded'], {'String': Object});
            }
            if (data.hasOwnProperty('matchGroupName')) {
                obj['matchGroupName'] = ApiClient.convertToType(data['matchGroupName'], 'String');
            }
            if (data.hasOwnProperty('rankings')) {
                obj['rankings'] = ApiClient.convertToType(data['rankings'], [LeagueRankingsEntryDto]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CompetitionMatchGroupRankingsDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CompetitionMatchGroupRankingsDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['matchGroupName'] && !(typeof data['matchGroupName'] === 'string' || data['matchGroupName'] instanceof String)) {
            throw new Error("Expected the field `matchGroupName` to be a primitive type in the JSON string but got " + data['matchGroupName']);
        }
        if (data['rankings']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['rankings'])) {
                throw new Error("Expected the field `rankings` to be an array in the JSON data but got " + data['rankings']);
            }
            // validate the optional field `rankings` (array)
            for (const item of data['rankings']) {
                LeagueRankingsEntryDto.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Entity unique identifier
 * @member {String} uuid
 */
CompetitionMatchGroupRankingsDto.prototype['uuid'] = undefined;

/**
 * @member {Object.<String, module:model/LinkDto>} _links
 */
CompetitionMatchGroupRankingsDto.prototype['_links'] = undefined;

/**
 * @member {Object.<String, Object>} _embedded
 */
CompetitionMatchGroupRankingsDto.prototype['_embedded'] = undefined;

/**
 * @member {String} matchGroupName
 */
CompetitionMatchGroupRankingsDto.prototype['matchGroupName'] = undefined;

/**
 * @member {Array.<module:model/LeagueRankingsEntryDto>} rankings
 */
CompetitionMatchGroupRankingsDto.prototype['rankings'] = undefined;






export default CompetitionMatchGroupRankingsDto;

