/**
 * SAMS REST API v2
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CompetitionMatchGroupDto from './CompetitionMatchGroupDto';
import LinkDto from './LinkDto';

/**
 * The CompetitionMatchGroupPage model module.
 * @module model/CompetitionMatchGroupPage
 * @version 2.1
 */
class CompetitionMatchGroupPage {
    /**
     * Constructs a new <code>CompetitionMatchGroupPage</code>.
     * @alias module:model/CompetitionMatchGroupPage
     */
    constructor() { 
        
        CompetitionMatchGroupPage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompetitionMatchGroupPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompetitionMatchGroupPage} obj Optional instance to populate.
     * @return {module:model/CompetitionMatchGroupPage} The populated <code>CompetitionMatchGroupPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompetitionMatchGroupPage();

            if (data.hasOwnProperty('totalElements')) {
                obj['totalElements'] = ApiClient.convertToType(data['totalElements'], 'Number');
            }
            if (data.hasOwnProperty('numberOfElements')) {
                obj['numberOfElements'] = ApiClient.convertToType(data['numberOfElements'], 'Number');
            }
            if (data.hasOwnProperty('_links')) {
                obj['_links'] = ApiClient.convertToType(data['_links'], {'String': LinkDto});
            }
            if (data.hasOwnProperty('_embedded')) {
                obj['_embedded'] = ApiClient.convertToType(data['_embedded'], {'String': Object});
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], [CompetitionMatchGroupDto]);
            }
            if (data.hasOwnProperty('empty')) {
                obj['empty'] = ApiClient.convertToType(data['empty'], 'Boolean');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('first')) {
                obj['first'] = ApiClient.convertToType(data['first'], 'Boolean');
            }
            if (data.hasOwnProperty('last')) {
                obj['last'] = ApiClient.convertToType(data['last'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CompetitionMatchGroupPage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CompetitionMatchGroupPage</code>.
     */
    static validateJSON(data) {
        if (data['content']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['content'])) {
                throw new Error("Expected the field `content` to be an array in the JSON data but got " + data['content']);
            }
            // validate the optional field `content` (array)
            for (const item of data['content']) {
                CompetitionMatchGroupDto.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} totalElements
 */
CompetitionMatchGroupPage.prototype['totalElements'] = undefined;

/**
 * @member {Number} numberOfElements
 */
CompetitionMatchGroupPage.prototype['numberOfElements'] = undefined;

/**
 * @member {Object.<String, module:model/LinkDto>} _links
 */
CompetitionMatchGroupPage.prototype['_links'] = undefined;

/**
 * @member {Object.<String, Object>} _embedded
 */
CompetitionMatchGroupPage.prototype['_embedded'] = undefined;

/**
 * @member {Array.<module:model/CompetitionMatchGroupDto>} content
 */
CompetitionMatchGroupPage.prototype['content'] = undefined;

/**
 * @member {Boolean} empty
 */
CompetitionMatchGroupPage.prototype['empty'] = undefined;

/**
 * @member {Number} totalPages
 */
CompetitionMatchGroupPage.prototype['totalPages'] = undefined;

/**
 * @member {Boolean} first
 */
CompetitionMatchGroupPage.prototype['first'] = undefined;

/**
 * @member {Boolean} last
 */
CompetitionMatchGroupPage.prototype['last'] = undefined;






export default CompetitionMatchGroupPage;

