/**
 * SAMS REST API v2
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LinkDto from './LinkDto';

/**
 * The CompetitionMatchGroupDto model module.
 * @module model/CompetitionMatchGroupDto
 * @version 2.1
 */
class CompetitionMatchGroupDto {
    /**
     * Constructs a new <code>CompetitionMatchGroupDto</code>.
     * @alias module:model/CompetitionMatchGroupDto
     */
    constructor() { 
        
        CompetitionMatchGroupDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompetitionMatchGroupDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompetitionMatchGroupDto} obj Optional instance to populate.
     * @return {module:model/CompetitionMatchGroupDto} The populated <code>CompetitionMatchGroupDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompetitionMatchGroupDto();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('_links')) {
                obj['_links'] = ApiClient.convertToType(data['_links'], {'String': LinkDto});
            }
            if (data.hasOwnProperty('_embedded')) {
                obj['_embedded'] = ApiClient.convertToType(data['_embedded'], {'String': Object});
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('tourneyLevel')) {
                obj['tourneyLevel'] = ApiClient.convertToType(data['tourneyLevel'], 'Number');
            }
            if (data.hasOwnProperty('seasonUuid')) {
                obj['seasonUuid'] = ApiClient.convertToType(data['seasonUuid'], 'String');
            }
            if (data.hasOwnProperty('competitionUuid')) {
                obj['competitionUuid'] = ApiClient.convertToType(data['competitionUuid'], 'String');
            }
            if (data.hasOwnProperty('associationUuid')) {
                obj['associationUuid'] = ApiClient.convertToType(data['associationUuid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CompetitionMatchGroupDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CompetitionMatchGroupDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['seasonUuid'] && !(typeof data['seasonUuid'] === 'string' || data['seasonUuid'] instanceof String)) {
            throw new Error("Expected the field `seasonUuid` to be a primitive type in the JSON string but got " + data['seasonUuid']);
        }
        // ensure the json data is a string
        if (data['competitionUuid'] && !(typeof data['competitionUuid'] === 'string' || data['competitionUuid'] instanceof String)) {
            throw new Error("Expected the field `competitionUuid` to be a primitive type in the JSON string but got " + data['competitionUuid']);
        }
        // ensure the json data is a string
        if (data['associationUuid'] && !(typeof data['associationUuid'] === 'string' || data['associationUuid'] instanceof String)) {
            throw new Error("Expected the field `associationUuid` to be a primitive type in the JSON string but got " + data['associationUuid']);
        }

        return true;
    }


}



/**
 * Entity unique identifier
 * @member {String} uuid
 */
CompetitionMatchGroupDto.prototype['uuid'] = undefined;

/**
 * @member {Object.<String, module:model/LinkDto>} _links
 */
CompetitionMatchGroupDto.prototype['_links'] = undefined;

/**
 * @member {Object.<String, Object>} _embedded
 */
CompetitionMatchGroupDto.prototype['_embedded'] = undefined;

/**
 * @member {String} name
 */
CompetitionMatchGroupDto.prototype['name'] = undefined;

/**
 * @member {Number} tourneyLevel
 */
CompetitionMatchGroupDto.prototype['tourneyLevel'] = undefined;

/**
 * @member {String} seasonUuid
 */
CompetitionMatchGroupDto.prototype['seasonUuid'] = undefined;

/**
 * @member {String} competitionUuid
 */
CompetitionMatchGroupDto.prototype['competitionUuid'] = undefined;

/**
 * @member {String} associationUuid
 */
CompetitionMatchGroupDto.prototype['associationUuid'] = undefined;






export default CompetitionMatchGroupDto;

