/**
 * SAMS REST API v2
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConstraintViolation model module.
 * @module model/ConstraintViolation
 * @version 2.1
 */
class ConstraintViolation {
    /**
     * Constructs a new <code>ConstraintViolation</code>.
     * @alias module:model/ConstraintViolation
     */
    constructor() { 
        
        ConstraintViolation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConstraintViolation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConstraintViolation} obj Optional instance to populate.
     * @return {module:model/ConstraintViolation} The populated <code>ConstraintViolation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConstraintViolation();

            if (data.hasOwnProperty('constraint')) {
                obj['constraint'] = ApiClient.convertToType(data['constraint'], 'String');
            }
            if (data.hasOwnProperty('property')) {
                obj['property'] = ApiClient.convertToType(data['property'], 'String');
            }
            if (data.hasOwnProperty('entity')) {
                obj['entity'] = ApiClient.convertToType(data['entity'], 'String');
            }
            if (data.hasOwnProperty('invalidValue')) {
                obj['invalidValue'] = ApiClient.convertToType(data['invalidValue'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConstraintViolation</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConstraintViolation</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['constraint'] && !(typeof data['constraint'] === 'string' || data['constraint'] instanceof String)) {
            throw new Error("Expected the field `constraint` to be a primitive type in the JSON string but got " + data['constraint']);
        }
        // ensure the json data is a string
        if (data['property'] && !(typeof data['property'] === 'string' || data['property'] instanceof String)) {
            throw new Error("Expected the field `property` to be a primitive type in the JSON string but got " + data['property']);
        }
        // ensure the json data is a string
        if (data['entity'] && !(typeof data['entity'] === 'string' || data['entity'] instanceof String)) {
            throw new Error("Expected the field `entity` to be a primitive type in the JSON string but got " + data['entity']);
        }
        // ensure the json data is a string
        if (data['invalidValue'] && !(typeof data['invalidValue'] === 'string' || data['invalidValue'] instanceof String)) {
            throw new Error("Expected the field `invalidValue` to be a primitive type in the JSON string but got " + data['invalidValue']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}



/**
 * @member {String} constraint
 */
ConstraintViolation.prototype['constraint'] = undefined;

/**
 * @member {String} property
 */
ConstraintViolation.prototype['property'] = undefined;

/**
 * @member {String} entity
 */
ConstraintViolation.prototype['entity'] = undefined;

/**
 * @member {String} invalidValue
 */
ConstraintViolation.prototype['invalidValue'] = undefined;

/**
 * @member {String} message
 */
ConstraintViolation.prototype['message'] = undefined;






export default ConstraintViolation;

