/**
 * SAMS REST API v2
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LinkDto from './LinkDto';
import Location from './Location';

/**
 * The Event model module.
 * @module model/Event
 * @version 2.1
 */
class Event {
    /**
     * Constructs a new <code>Event</code>.
     * @alias module:model/Event
     */
    constructor() { 
        
        Event.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Event</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Event} obj Optional instance to populate.
     * @return {module:model/Event} The populated <code>Event</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Event();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('_links')) {
                obj['_links'] = ApiClient.convertToType(data['_links'], {'String': LinkDto});
            }
            if (data.hasOwnProperty('_embedded')) {
                obj['_embedded'] = ApiClient.convertToType(data['_embedded'], {'String': Object});
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('shortname')) {
                obj['shortname'] = ApiClient.convertToType(data['shortname'], 'String');
            }
            if (data.hasOwnProperty('eventNumber')) {
                obj['eventNumber'] = ApiClient.convertToType(data['eventNumber'], 'Number');
            }
            if (data.hasOwnProperty('overridingEventNumber')) {
                obj['overridingEventNumber'] = ApiClient.convertToType(data['overridingEventNumber'], 'String');
            }
            if (data.hasOwnProperty('dateNotYetKnown')) {
                obj['dateNotYetKnown'] = ApiClient.convertToType(data['dateNotYetKnown'], 'Boolean');
            }
            if (data.hasOwnProperty('endsAt')) {
                obj['endsAt'] = ApiClient.convertToType(data['endsAt'], 'Date');
            }
            if (data.hasOwnProperty('beginsAt')) {
                obj['beginsAt'] = ApiClient.convertToType(data['beginsAt'], 'Date');
            }
            if (data.hasOwnProperty('registrationDeadline')) {
                obj['registrationDeadline'] = ApiClient.convertToType(data['registrationDeadline'], 'Date');
            }
            if (data.hasOwnProperty('associationUuid')) {
                obj['associationUuid'] = ApiClient.convertToType(data['associationUuid'], 'String');
            }
            if (data.hasOwnProperty('canceled')) {
                obj['canceled'] = ApiClient.convertToType(data['canceled'], 'Boolean');
            }
            if (data.hasOwnProperty('minimumNumberOfParticipants')) {
                obj['minimumNumberOfParticipants'] = ApiClient.convertToType(data['minimumNumberOfParticipants'], 'Number');
            }
            if (data.hasOwnProperty('maximumNumberOfParticipants')) {
                obj['maximumNumberOfParticipants'] = ApiClient.convertToType(data['maximumNumberOfParticipants'], 'Number');
            }
            if (data.hasOwnProperty('usedCapacity')) {
                obj['usedCapacity'] = ApiClient.convertToType(data['usedCapacity'], 'Number');
            }
            if (data.hasOwnProperty('registrationUri')) {
                obj['registrationUri'] = ApiClient.convertToType(data['registrationUri'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = Location.constructFromObject(data['location']);
            }
            if (data.hasOwnProperty('eventTypeUuid')) {
                obj['eventTypeUuid'] = ApiClient.convertToType(data['eventTypeUuid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Event</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Event</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['shortname'] && !(typeof data['shortname'] === 'string' || data['shortname'] instanceof String)) {
            throw new Error("Expected the field `shortname` to be a primitive type in the JSON string but got " + data['shortname']);
        }
        // ensure the json data is a string
        if (data['overridingEventNumber'] && !(typeof data['overridingEventNumber'] === 'string' || data['overridingEventNumber'] instanceof String)) {
            throw new Error("Expected the field `overridingEventNumber` to be a primitive type in the JSON string but got " + data['overridingEventNumber']);
        }
        // ensure the json data is a string
        if (data['associationUuid'] && !(typeof data['associationUuid'] === 'string' || data['associationUuid'] instanceof String)) {
            throw new Error("Expected the field `associationUuid` to be a primitive type in the JSON string but got " + data['associationUuid']);
        }
        // ensure the json data is a string
        if (data['registrationUri'] && !(typeof data['registrationUri'] === 'string' || data['registrationUri'] instanceof String)) {
            throw new Error("Expected the field `registrationUri` to be a primitive type in the JSON string but got " + data['registrationUri']);
        }
        // validate the optional field `location`
        if (data['location']) { // data not null
          Location.validateJSON(data['location']);
        }
        // ensure the json data is a string
        if (data['eventTypeUuid'] && !(typeof data['eventTypeUuid'] === 'string' || data['eventTypeUuid'] instanceof String)) {
            throw new Error("Expected the field `eventTypeUuid` to be a primitive type in the JSON string but got " + data['eventTypeUuid']);
        }

        return true;
    }


}



/**
 * Entity unique identifier
 * @member {String} uuid
 */
Event.prototype['uuid'] = undefined;

/**
 * @member {Object.<String, module:model/LinkDto>} _links
 */
Event.prototype['_links'] = undefined;

/**
 * @member {Object.<String, Object>} _embedded
 */
Event.prototype['_embedded'] = undefined;

/**
 * @member {String} name
 */
Event.prototype['name'] = undefined;

/**
 * @member {String} shortname
 */
Event.prototype['shortname'] = undefined;

/**
 * @member {Number} eventNumber
 */
Event.prototype['eventNumber'] = undefined;

/**
 * @member {String} overridingEventNumber
 */
Event.prototype['overridingEventNumber'] = undefined;

/**
 * True if no start and end date has been set yet
 * @member {Boolean} dateNotYetKnown
 */
Event.prototype['dateNotYetKnown'] = undefined;

/**
 * @member {Date} endsAt
 */
Event.prototype['endsAt'] = undefined;

/**
 * Start date for an event. Is null if dateNotYetKnown is true
 * @member {Date} beginsAt
 */
Event.prototype['beginsAt'] = undefined;

/**
 * @member {Date} registrationDeadline
 */
Event.prototype['registrationDeadline'] = undefined;

/**
 * @member {String} associationUuid
 */
Event.prototype['associationUuid'] = undefined;

/**
 * True if the event has been canceled
 * @member {Boolean} canceled
 */
Event.prototype['canceled'] = undefined;

/**
 * @member {Number} minimumNumberOfParticipants
 */
Event.prototype['minimumNumberOfParticipants'] = undefined;

/**
 * @member {Number} maximumNumberOfParticipants
 */
Event.prototype['maximumNumberOfParticipants'] = undefined;

/**
 * Number of registered participants for an event. If this event is a subordinate event, i.e. there is a higher level event, then this value is calculated as the sum of all participants of the higher level event and all participants of this higher level event's subordinate event. If this event has subordinate events, then this value is calculated as the sum of participants of this event and all its subordinate events.
 * @member {Number} usedCapacity
 */
Event.prototype['usedCapacity'] = undefined;

/**
 * @member {String} registrationUri
 */
Event.prototype['registrationUri'] = undefined;

/**
 * @member {module:model/Location} location
 */
Event.prototype['location'] = undefined;

/**
 * Reference to the type details for this event
 * @member {String} eventTypeUuid
 */
Event.prototype['eventTypeUuid'] = undefined;






export default Event;

