<?php
/**
 * Event
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SAMS REST API v2
 *
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Event Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Event implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Event';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'uuid' => 'string',
        '_links' => 'array<string,\OpenAPI\Client\Model\LinkDto>',
        '_embedded' => 'array<string,object>',
        'name' => 'string',
        'shortname' => 'string',
        'event_number' => 'int',
        'overriding_event_number' => 'string',
        'date_not_yet_known' => 'bool',
        'ends_at' => '\DateTime',
        'begins_at' => '\DateTime',
        'registration_deadline' => '\DateTime',
        'association_uuid' => 'string',
        'canceled' => 'bool',
        'minimum_number_of_participants' => 'int',
        'maximum_number_of_participants' => 'int',
        'used_capacity' => 'int',
        'registration_uri' => 'string',
        'location' => '\OpenAPI\Client\Model\Location',
        'event_type_uuid' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'uuid' => null,
        '_links' => null,
        '_embedded' => null,
        'name' => null,
        'shortname' => null,
        'event_number' => 'int32',
        'overriding_event_number' => null,
        'date_not_yet_known' => null,
        'ends_at' => 'date-time',
        'begins_at' => 'date-time',
        'registration_deadline' => 'date-time',
        'association_uuid' => null,
        'canceled' => null,
        'minimum_number_of_participants' => 'int32',
        'maximum_number_of_participants' => 'int32',
        'used_capacity' => 'int32',
        'registration_uri' => 'uri',
        'location' => null,
        'event_type_uuid' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'uuid' => false,
        '_links' => false,
        '_embedded' => false,
        'name' => false,
        'shortname' => false,
        'event_number' => false,
        'overriding_event_number' => false,
        'date_not_yet_known' => false,
        'ends_at' => false,
        'begins_at' => false,
        'registration_deadline' => false,
        'association_uuid' => false,
        'canceled' => false,
        'minimum_number_of_participants' => false,
        'maximum_number_of_participants' => false,
        'used_capacity' => false,
        'registration_uri' => false,
        'location' => false,
        'event_type_uuid' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid' => 'uuid',
        '_links' => '_links',
        '_embedded' => '_embedded',
        'name' => 'name',
        'shortname' => 'shortname',
        'event_number' => 'eventNumber',
        'overriding_event_number' => 'overridingEventNumber',
        'date_not_yet_known' => 'dateNotYetKnown',
        'ends_at' => 'endsAt',
        'begins_at' => 'beginsAt',
        'registration_deadline' => 'registrationDeadline',
        'association_uuid' => 'associationUuid',
        'canceled' => 'canceled',
        'minimum_number_of_participants' => 'minimumNumberOfParticipants',
        'maximum_number_of_participants' => 'maximumNumberOfParticipants',
        'used_capacity' => 'usedCapacity',
        'registration_uri' => 'registrationUri',
        'location' => 'location',
        'event_type_uuid' => 'eventTypeUuid'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uuid' => 'setUuid',
        '_links' => 'setLinks',
        '_embedded' => 'setEmbedded',
        'name' => 'setName',
        'shortname' => 'setShortname',
        'event_number' => 'setEventNumber',
        'overriding_event_number' => 'setOverridingEventNumber',
        'date_not_yet_known' => 'setDateNotYetKnown',
        'ends_at' => 'setEndsAt',
        'begins_at' => 'setBeginsAt',
        'registration_deadline' => 'setRegistrationDeadline',
        'association_uuid' => 'setAssociationUuid',
        'canceled' => 'setCanceled',
        'minimum_number_of_participants' => 'setMinimumNumberOfParticipants',
        'maximum_number_of_participants' => 'setMaximumNumberOfParticipants',
        'used_capacity' => 'setUsedCapacity',
        'registration_uri' => 'setRegistrationUri',
        'location' => 'setLocation',
        'event_type_uuid' => 'setEventTypeUuid'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uuid' => 'getUuid',
        '_links' => 'getLinks',
        '_embedded' => 'getEmbedded',
        'name' => 'getName',
        'shortname' => 'getShortname',
        'event_number' => 'getEventNumber',
        'overriding_event_number' => 'getOverridingEventNumber',
        'date_not_yet_known' => 'getDateNotYetKnown',
        'ends_at' => 'getEndsAt',
        'begins_at' => 'getBeginsAt',
        'registration_deadline' => 'getRegistrationDeadline',
        'association_uuid' => 'getAssociationUuid',
        'canceled' => 'getCanceled',
        'minimum_number_of_participants' => 'getMinimumNumberOfParticipants',
        'maximum_number_of_participants' => 'getMaximumNumberOfParticipants',
        'used_capacity' => 'getUsedCapacity',
        'registration_uri' => 'getRegistrationUri',
        'location' => 'getLocation',
        'event_type_uuid' => 'getEventTypeUuid'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('uuid', $data ?? [], null);
        $this->setIfExists('_links', $data ?? [], null);
        $this->setIfExists('_embedded', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('shortname', $data ?? [], null);
        $this->setIfExists('event_number', $data ?? [], null);
        $this->setIfExists('overriding_event_number', $data ?? [], null);
        $this->setIfExists('date_not_yet_known', $data ?? [], null);
        $this->setIfExists('ends_at', $data ?? [], null);
        $this->setIfExists('begins_at', $data ?? [], null);
        $this->setIfExists('registration_deadline', $data ?? [], null);
        $this->setIfExists('association_uuid', $data ?? [], null);
        $this->setIfExists('canceled', $data ?? [], null);
        $this->setIfExists('minimum_number_of_participants', $data ?? [], null);
        $this->setIfExists('maximum_number_of_participants', $data ?? [], null);
        $this->setIfExists('used_capacity', $data ?? [], null);
        $this->setIfExists('registration_uri', $data ?? [], null);
        $this->setIfExists('location', $data ?? [], null);
        $this->setIfExists('event_type_uuid', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uuid
     *
     * @return string|null
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string|null $uuid Entity unique identifier
     *
     * @return self
     */
    public function setUuid($uuid)
    {
        if (is_null($uuid)) {
            throw new \InvalidArgumentException('non-nullable uuid cannot be null');
        }
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets _links
     *
     * @return array<string,\OpenAPI\Client\Model\LinkDto>|null
     */
    public function getLinks()
    {
        return $this->container['_links'];
    }

    /**
     * Sets _links
     *
     * @param array<string,\OpenAPI\Client\Model\LinkDto>|null $_links _links
     *
     * @return self
     */
    public function setLinks($_links)
    {
        if (is_null($_links)) {
            throw new \InvalidArgumentException('non-nullable _links cannot be null');
        }
        $this->container['_links'] = $_links;

        return $this;
    }

    /**
     * Gets _embedded
     *
     * @return array<string,object>|null
     */
    public function getEmbedded()
    {
        return $this->container['_embedded'];
    }

    /**
     * Sets _embedded
     *
     * @param array<string,object>|null $_embedded _embedded
     *
     * @return self
     */
    public function setEmbedded($_embedded)
    {
        if (is_null($_embedded)) {
            throw new \InvalidArgumentException('non-nullable _embedded cannot be null');
        }
        $this->container['_embedded'] = $_embedded;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets shortname
     *
     * @return string|null
     */
    public function getShortname()
    {
        return $this->container['shortname'];
    }

    /**
     * Sets shortname
     *
     * @param string|null $shortname shortname
     *
     * @return self
     */
    public function setShortname($shortname)
    {
        if (is_null($shortname)) {
            throw new \InvalidArgumentException('non-nullable shortname cannot be null');
        }
        $this->container['shortname'] = $shortname;

        return $this;
    }

    /**
     * Gets event_number
     *
     * @return int|null
     */
    public function getEventNumber()
    {
        return $this->container['event_number'];
    }

    /**
     * Sets event_number
     *
     * @param int|null $event_number event_number
     *
     * @return self
     */
    public function setEventNumber($event_number)
    {
        if (is_null($event_number)) {
            throw new \InvalidArgumentException('non-nullable event_number cannot be null');
        }
        $this->container['event_number'] = $event_number;

        return $this;
    }

    /**
     * Gets overriding_event_number
     *
     * @return string|null
     */
    public function getOverridingEventNumber()
    {
        return $this->container['overriding_event_number'];
    }

    /**
     * Sets overriding_event_number
     *
     * @param string|null $overriding_event_number overriding_event_number
     *
     * @return self
     */
    public function setOverridingEventNumber($overriding_event_number)
    {
        if (is_null($overriding_event_number)) {
            throw new \InvalidArgumentException('non-nullable overriding_event_number cannot be null');
        }
        $this->container['overriding_event_number'] = $overriding_event_number;

        return $this;
    }

    /**
     * Gets date_not_yet_known
     *
     * @return bool|null
     */
    public function getDateNotYetKnown()
    {
        return $this->container['date_not_yet_known'];
    }

    /**
     * Sets date_not_yet_known
     *
     * @param bool|null $date_not_yet_known True if no start and end date has been set yet
     *
     * @return self
     */
    public function setDateNotYetKnown($date_not_yet_known)
    {
        if (is_null($date_not_yet_known)) {
            throw new \InvalidArgumentException('non-nullable date_not_yet_known cannot be null');
        }
        $this->container['date_not_yet_known'] = $date_not_yet_known;

        return $this;
    }

    /**
     * Gets ends_at
     *
     * @return \DateTime|null
     */
    public function getEndsAt()
    {
        return $this->container['ends_at'];
    }

    /**
     * Sets ends_at
     *
     * @param \DateTime|null $ends_at ends_at
     *
     * @return self
     */
    public function setEndsAt($ends_at)
    {
        if (is_null($ends_at)) {
            throw new \InvalidArgumentException('non-nullable ends_at cannot be null');
        }
        $this->container['ends_at'] = $ends_at;

        return $this;
    }

    /**
     * Gets begins_at
     *
     * @return \DateTime|null
     */
    public function getBeginsAt()
    {
        return $this->container['begins_at'];
    }

    /**
     * Sets begins_at
     *
     * @param \DateTime|null $begins_at Start date for an event. Is null if dateNotYetKnown is true
     *
     * @return self
     */
    public function setBeginsAt($begins_at)
    {
        if (is_null($begins_at)) {
            throw new \InvalidArgumentException('non-nullable begins_at cannot be null');
        }
        $this->container['begins_at'] = $begins_at;

        return $this;
    }

    /**
     * Gets registration_deadline
     *
     * @return \DateTime|null
     */
    public function getRegistrationDeadline()
    {
        return $this->container['registration_deadline'];
    }

    /**
     * Sets registration_deadline
     *
     * @param \DateTime|null $registration_deadline registration_deadline
     *
     * @return self
     */
    public function setRegistrationDeadline($registration_deadline)
    {
        if (is_null($registration_deadline)) {
            throw new \InvalidArgumentException('non-nullable registration_deadline cannot be null');
        }
        $this->container['registration_deadline'] = $registration_deadline;

        return $this;
    }

    /**
     * Gets association_uuid
     *
     * @return string|null
     */
    public function getAssociationUuid()
    {
        return $this->container['association_uuid'];
    }

    /**
     * Sets association_uuid
     *
     * @param string|null $association_uuid association_uuid
     *
     * @return self
     */
    public function setAssociationUuid($association_uuid)
    {
        if (is_null($association_uuid)) {
            throw new \InvalidArgumentException('non-nullable association_uuid cannot be null');
        }
        $this->container['association_uuid'] = $association_uuid;

        return $this;
    }

    /**
     * Gets canceled
     *
     * @return bool|null
     */
    public function getCanceled()
    {
        return $this->container['canceled'];
    }

    /**
     * Sets canceled
     *
     * @param bool|null $canceled True if the event has been canceled
     *
     * @return self
     */
    public function setCanceled($canceled)
    {
        if (is_null($canceled)) {
            throw new \InvalidArgumentException('non-nullable canceled cannot be null');
        }
        $this->container['canceled'] = $canceled;

        return $this;
    }

    /**
     * Gets minimum_number_of_participants
     *
     * @return int|null
     */
    public function getMinimumNumberOfParticipants()
    {
        return $this->container['minimum_number_of_participants'];
    }

    /**
     * Sets minimum_number_of_participants
     *
     * @param int|null $minimum_number_of_participants minimum_number_of_participants
     *
     * @return self
     */
    public function setMinimumNumberOfParticipants($minimum_number_of_participants)
    {
        if (is_null($minimum_number_of_participants)) {
            throw new \InvalidArgumentException('non-nullable minimum_number_of_participants cannot be null');
        }
        $this->container['minimum_number_of_participants'] = $minimum_number_of_participants;

        return $this;
    }

    /**
     * Gets maximum_number_of_participants
     *
     * @return int|null
     */
    public function getMaximumNumberOfParticipants()
    {
        return $this->container['maximum_number_of_participants'];
    }

    /**
     * Sets maximum_number_of_participants
     *
     * @param int|null $maximum_number_of_participants maximum_number_of_participants
     *
     * @return self
     */
    public function setMaximumNumberOfParticipants($maximum_number_of_participants)
    {
        if (is_null($maximum_number_of_participants)) {
            throw new \InvalidArgumentException('non-nullable maximum_number_of_participants cannot be null');
        }
        $this->container['maximum_number_of_participants'] = $maximum_number_of_participants;

        return $this;
    }

    /**
     * Gets used_capacity
     *
     * @return int|null
     */
    public function getUsedCapacity()
    {
        return $this->container['used_capacity'];
    }

    /**
     * Sets used_capacity
     *
     * @param int|null $used_capacity Number of registered participants for an event. If this event is a subordinate event, i.e. there is a higher level event, then this value is calculated as the sum of all participants of the higher level event and all participants of this higher level event's subordinate event. If this event has subordinate events, then this value is calculated as the sum of participants of this event and all its subordinate events.
     *
     * @return self
     */
    public function setUsedCapacity($used_capacity)
    {
        if (is_null($used_capacity)) {
            throw new \InvalidArgumentException('non-nullable used_capacity cannot be null');
        }
        $this->container['used_capacity'] = $used_capacity;

        return $this;
    }

    /**
     * Gets registration_uri
     *
     * @return string|null
     */
    public function getRegistrationUri()
    {
        return $this->container['registration_uri'];
    }

    /**
     * Sets registration_uri
     *
     * @param string|null $registration_uri registration_uri
     *
     * @return self
     */
    public function setRegistrationUri($registration_uri)
    {
        if (is_null($registration_uri)) {
            throw new \InvalidArgumentException('non-nullable registration_uri cannot be null');
        }
        $this->container['registration_uri'] = $registration_uri;

        return $this;
    }

    /**
     * Gets location
     *
     * @return \OpenAPI\Client\Model\Location|null
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param \OpenAPI\Client\Model\Location|null $location location
     *
     * @return self
     */
    public function setLocation($location)
    {
        if (is_null($location)) {
            throw new \InvalidArgumentException('non-nullable location cannot be null');
        }
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets event_type_uuid
     *
     * @return string|null
     */
    public function getEventTypeUuid()
    {
        return $this->container['event_type_uuid'];
    }

    /**
     * Sets event_type_uuid
     *
     * @param string|null $event_type_uuid Reference to the type details for this event
     *
     * @return self
     */
    public function setEventTypeUuid($event_type_uuid)
    {
        if (is_null($event_type_uuid)) {
            throw new \InvalidArgumentException('non-nullable event_type_uuid cannot be null');
        }
        $this->container['event_type_uuid'] = $event_type_uuid;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


