<?php
/**
 * LeagueHierarchyDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SAMSPlugin\RestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SAMS REST API v2
 *
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SAMSPlugin\RestClient\Model;

use \ArrayAccess;
use \SAMSPlugin\RestClient\ObjectSerializer;

/**
 * LeagueHierarchyDto Class Doc Comment
 *
 * @category Class
 * @package  SAMSPlugin\RestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LeagueHierarchyDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LeagueHierarchyDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'uuid' => 'string',
        '_links' => 'array<string,\SAMSPlugin\RestClient\Model\LinkDto>',
        '_embedded' => 'array<string,object>',
        'name' => 'string',
        'short_name' => 'string',
        'season_uuid' => 'string',
        'association_uuid' => 'string',
        'level' => 'int',
        'parent_league_hierarchy_uuid' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'uuid' => null,
        '_links' => null,
        '_embedded' => null,
        'name' => null,
        'short_name' => null,
        'season_uuid' => null,
        'association_uuid' => null,
        'level' => 'int32',
        'parent_league_hierarchy_uuid' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'uuid' => false,
        '_links' => false,
        '_embedded' => false,
        'name' => false,
        'short_name' => false,
        'season_uuid' => false,
        'association_uuid' => false,
        'level' => false,
        'parent_league_hierarchy_uuid' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'uuid' => 'uuid',
        '_links' => '_links',
        '_embedded' => '_embedded',
        'name' => 'name',
        'short_name' => 'shortName',
        'season_uuid' => 'seasonUuid',
        'association_uuid' => 'associationUuid',
        'level' => 'level',
        'parent_league_hierarchy_uuid' => 'parentLeagueHierarchyUuid'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'uuid' => 'setUuid',
        '_links' => 'setLinks',
        '_embedded' => 'setEmbedded',
        'name' => 'setName',
        'short_name' => 'setShortName',
        'season_uuid' => 'setSeasonUuid',
        'association_uuid' => 'setAssociationUuid',
        'level' => 'setLevel',
        'parent_league_hierarchy_uuid' => 'setParentLeagueHierarchyUuid'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'uuid' => 'getUuid',
        '_links' => 'getLinks',
        '_embedded' => 'getEmbedded',
        'name' => 'getName',
        'short_name' => 'getShortName',
        'season_uuid' => 'getSeasonUuid',
        'association_uuid' => 'getAssociationUuid',
        'level' => 'getLevel',
        'parent_league_hierarchy_uuid' => 'getParentLeagueHierarchyUuid'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('uuid', $data ?? [], null);
        $this->setIfExists('_links', $data ?? [], null);
        $this->setIfExists('_embedded', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('short_name', $data ?? [], null);
        $this->setIfExists('season_uuid', $data ?? [], null);
        $this->setIfExists('association_uuid', $data ?? [], null);
        $this->setIfExists('level', $data ?? [], null);
        $this->setIfExists('parent_league_hierarchy_uuid', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets uuid
     *
     * @return string|null
     */
    public function getUuid()
    {
        return $this->container['uuid'];
    }

    /**
     * Sets uuid
     *
     * @param string|null $uuid Entity unique identifier
     *
     * @return self
     */
    public function setUuid($uuid)
    {
        if (is_null($uuid)) {
            throw new \InvalidArgumentException('non-nullable uuid cannot be null');
        }
        $this->container['uuid'] = $uuid;

        return $this;
    }

    /**
     * Gets _links
     *
     * @return array<string,\SAMSPlugin\RestClient\Model\LinkDto>|null
     */
    public function getLinks()
    {
        return $this->container['_links'];
    }

    /**
     * Sets _links
     *
     * @param array<string,\SAMSPlugin\RestClient\Model\LinkDto>|null $_links _links
     *
     * @return self
     */
    public function setLinks($_links)
    {
        if (is_null($_links)) {
            throw new \InvalidArgumentException('non-nullable _links cannot be null');
        }
        $this->container['_links'] = $_links;

        return $this;
    }

    /**
     * Gets _embedded
     *
     * @return array<string,object>|null
     */
    public function getEmbedded()
    {
        return $this->container['_embedded'];
    }

    /**
     * Sets _embedded
     *
     * @param array<string,object>|null $_embedded _embedded
     *
     * @return self
     */
    public function setEmbedded($_embedded)
    {
        if (is_null($_embedded)) {
            throw new \InvalidArgumentException('non-nullable _embedded cannot be null');
        }
        $this->container['_embedded'] = $_embedded;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets short_name
     *
     * @return string|null
     */
    public function getShortName()
    {
        return $this->container['short_name'];
    }

    /**
     * Sets short_name
     *
     * @param string|null $short_name short_name
     *
     * @return self
     */
    public function setShortName($short_name)
    {
        if (is_null($short_name)) {
            throw new \InvalidArgumentException('non-nullable short_name cannot be null');
        }
        $this->container['short_name'] = $short_name;

        return $this;
    }

    /**
     * Gets season_uuid
     *
     * @return string|null
     */
    public function getSeasonUuid()
    {
        return $this->container['season_uuid'];
    }

    /**
     * Sets season_uuid
     *
     * @param string|null $season_uuid season_uuid
     *
     * @return self
     */
    public function setSeasonUuid($season_uuid)
    {
        if (is_null($season_uuid)) {
            throw new \InvalidArgumentException('non-nullable season_uuid cannot be null');
        }
        $this->container['season_uuid'] = $season_uuid;

        return $this;
    }

    /**
     * Gets association_uuid
     *
     * @return string|null
     */
    public function getAssociationUuid()
    {
        return $this->container['association_uuid'];
    }

    /**
     * Sets association_uuid
     *
     * @param string|null $association_uuid association_uuid
     *
     * @return self
     */
    public function setAssociationUuid($association_uuid)
    {
        if (is_null($association_uuid)) {
            throw new \InvalidArgumentException('non-nullable association_uuid cannot be null');
        }
        $this->container['association_uuid'] = $association_uuid;

        return $this;
    }

    /**
     * Gets level
     *
     * @return int|null
     */
    public function getLevel()
    {
        return $this->container['level'];
    }

    /**
     * Sets level
     *
     * @param int|null $level level
     *
     * @return self
     */
    public function setLevel($level)
    {
        if (is_null($level)) {
            throw new \InvalidArgumentException('non-nullable level cannot be null');
        }
        $this->container['level'] = $level;

        return $this;
    }

    /**
     * Gets parent_league_hierarchy_uuid
     *
     * @return string|null
     */
    public function getParentLeagueHierarchyUuid()
    {
        return $this->container['parent_league_hierarchy_uuid'];
    }

    /**
     * Sets parent_league_hierarchy_uuid
     *
     * @param string|null $parent_league_hierarchy_uuid parent_league_hierarchy_uuid
     *
     * @return self
     */
    public function setParentLeagueHierarchyUuid($parent_league_hierarchy_uuid)
    {
        if (is_null($parent_league_hierarchy_uuid)) {
            throw new \InvalidArgumentException('non-nullable parent_league_hierarchy_uuid cannot be null');
        }
        $this->container['parent_league_hierarchy_uuid'] = $parent_league_hierarchy_uuid;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


