/**
 * SAMS REST API v2
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import LeagueMatchDayDto from '../model/LeagueMatchDayDto';
import LeagueMatchDayPage from '../model/LeagueMatchDayPage';
import LeagueMatchPage from '../model/LeagueMatchPage';
import ResponseException from '../model/ResponseException';
import ResponseExceptionMessage from '../model/ResponseExceptionMessage';
import ValidationError from '../model/ValidationError';

/**
* SAMSMatchDaysAPI service.
* @module api/SAMSMatchDaysAPIApi
* @version 2.1
*/
export default class SAMSMatchDaysAPIApi {

    /**
    * Constructs a new SAMSMatchDaysAPIApi. 
    * @alias module:api/SAMSMatchDaysAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAllMatchDays operation.
     * @callback module:api/SAMSMatchDaysAPIApi~getAllMatchDaysCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LeagueMatchDayPage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all available match days as a paged list.
     * The default page size is 20. The page size must not be greater than 100
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {String} [association] Filter for association using the given UUID. Defaults to no filtering.
     * @param {module:api/SAMSMatchDaysAPIApi~getAllMatchDaysCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LeagueMatchDayPage}
     */
    getAllMatchDays(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'association': opts['association']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = LeagueMatchDayPage;
      return this.apiClient.callApi(
        '/match-days', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getMatchDayByUuid operation.
     * @callback module:api/SAMSMatchDaysAPIApi~getMatchDayByUuidCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LeagueMatchDayDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a match day identified by the given UUID
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {module:api/SAMSMatchDaysAPIApi~getMatchDayByUuidCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LeagueMatchDayDto}
     */
    getMatchDayByUuid(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getMatchDayByUuid");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = LeagueMatchDayDto;
      return this.apiClient.callApi(
        '/match-days/{uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getMatchesByMatchDay operation.
     * @callback module:api/SAMSMatchDaysAPIApi~getMatchesByMatchDayCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LeagueMatchPage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all matches of a match day based on the given UUID. The default page size is 20. The page size must not be greater than 100
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {module:api/SAMSMatchDaysAPIApi~getMatchesByMatchDayCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LeagueMatchPage}
     */
    getMatchesByMatchDay(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getMatchesByMatchDay");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = LeagueMatchPage;
      return this.apiClient.callApi(
        '/match-days/{uuid}/league-matches', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
