/**
 * SAMS REST API v2
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import LeagueDto from '../model/LeagueDto';
import LeagueMatchDayPage from '../model/LeagueMatchDayPage';
import LeaguePage from '../model/LeaguePage';
import LeagueRankingsResourcePage from '../model/LeagueRankingsResourcePage';
import ResponseException from '../model/ResponseException';
import ResponseExceptionMessage from '../model/ResponseExceptionMessage';
import TeamPage from '../model/TeamPage';
import ValidationError from '../model/ValidationError';

/**
* SAMSLeaguesAPI service.
* @module api/SAMSLeaguesAPIApi
* @version 2.1
*/
export default class SAMSLeaguesAPIApi {

    /**
    * Constructs a new SAMSLeaguesAPIApi. 
    * @alias module:api/SAMSLeaguesAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAllLeagues operation.
     * @callback module:api/SAMSLeaguesAPIApi~getAllLeaguesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LeaguePage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all available leagues as a paged list. The default page size is 20. The page size must not be greater than 100
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {String} [association] Filter for association using the given UUID. Defaults to no filtering.
     * @param {String} [season] Filter for season using the given UUID. Defaults to no filtering.
     * @param {module:api/SAMSLeaguesAPIApi~getAllLeaguesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LeaguePage}
     */
    getAllLeagues(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'association': opts['association'],
        'season': opts['season']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = LeaguePage;
      return this.apiClient.callApi(
        '/leagues', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getLeagueByUuid operation.
     * @callback module:api/SAMSLeaguesAPIApi~getLeagueByUuidCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LeagueDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a league identified by the given UUID
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {module:api/SAMSLeaguesAPIApi~getLeagueByUuidCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LeagueDto}
     */
    getLeagueByUuid(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getLeagueByUuid");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = LeagueDto;
      return this.apiClient.callApi(
        '/leagues/{uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getMatchDaysForLeague operation.
     * @callback module:api/SAMSLeaguesAPIApi~getMatchDaysForLeagueCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LeagueMatchDayPage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all match days corresponding to the league identified by the given UUID
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {module:api/SAMSLeaguesAPIApi~getMatchDaysForLeagueCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LeagueMatchDayPage}
     */
    getMatchDaysForLeague(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getMatchDaysForLeague");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = LeagueMatchDayPage;
      return this.apiClient.callApi(
        '/leagues/{uuid}/match-days', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getRankingsForLeague operation.
     * @callback module:api/SAMSLeaguesAPIApi~getRankingsForLeagueCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LeagueRankingsResourcePage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the rankings of a league identified by the given UUID.
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {module:api/SAMSLeaguesAPIApi~getRankingsForLeagueCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LeagueRankingsResourcePage}
     */
    getRankingsForLeague(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getRankingsForLeague");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = LeagueRankingsResourcePage;
      return this.apiClient.callApi(
        '/leagues/{uuid}/rankings', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTeamsForLeague operation.
     * @callback module:api/SAMSLeaguesAPIApi~getTeamsForLeagueCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TeamPage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all teams of a league identified by the given UUID as a paged list. The default page size is 20. The page size must not be greater than 100
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {module:api/SAMSLeaguesAPIApi~getTeamsForLeagueCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TeamPage}
     */
    getTeamsForLeague(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getTeamsForLeague");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = TeamPage;
      return this.apiClient.callApi(
        '/leagues/{uuid}/teams', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
