/**
 * SAMS REST API v2
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Association from '../model/Association';
import AssociationResourcePage from '../model/AssociationResourcePage';
import CommitteePage from '../model/CommitteePage';
import ResponseException from '../model/ResponseException';
import ResponseExceptionMessage from '../model/ResponseExceptionMessage';
import SportsclubPage from '../model/SportsclubPage';
import ValidationError from '../model/ValidationError';

/**
* SAMSAssociationsAPI service.
* @module api/SAMSAssociationsAPIApi
* @version 2.1
*/
export default class SAMSAssociationsAPIApi {

    /**
    * Constructs a new SAMSAssociationsAPIApi. 
    * @alias module:api/SAMSAssociationsAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAssociationByUuid operation.
     * @callback module:api/SAMSAssociationsAPIApi~getAssociationByUuidCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Association} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns an association identified by the given UUID
     * @param {String} uuid UUID of the requested association
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {module:api/SAMSAssociationsAPIApi~getAssociationByUuidCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Association}
     */
    getAssociationByUuid(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getAssociationByUuid");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json'];
      let returnType = Association;
      return this.apiClient.callApi(
        '/associations/{uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAssociations operation.
     * @callback module:api/SAMSAssociationsAPIApi~getAssociationsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AssociationResourcePage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all available associations.
     * Returns all available association as a paged list. The default page size is 20. The page size must not be greater than 100
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {String} [association] Filter for association using the given UUID. Defaults to no filtering.
     * @param {module:api/SAMSAssociationsAPIApi~getAssociationsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AssociationResourcePage}
     */
    getAssociations(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'association': opts['association']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json'];
      let returnType = AssociationResourcePage;
      return this.apiClient.callApi(
        '/associations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCommitteesForAssociation operation.
     * @callback module:api/SAMSAssociationsAPIApi~getCommitteesForAssociationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CommitteePage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the list of committees.
     * Returns the list of committees for an association as a paged list. The default page size is The returned committees list their respective members including the members' publicly available contact information.20. The page size must not be greater than 100
     * @param {String} uuid UUID of the association whose committees are requested
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {module:api/SAMSAssociationsAPIApi~getCommitteesForAssociationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CommitteePage}
     */
    getCommitteesForAssociation(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getCommitteesForAssociation");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json'];
      let returnType = CommitteePage;
      return this.apiClient.callApi(
        '/associations/{uuid}/committees', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSportsclubsForAssociation operation.
     * @callback module:api/SAMSAssociationsAPIApi~getSportsclubsForAssociationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SportsclubPage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the list of sportsclubs belonging to the association identified by the specified UUID as a paged list. The default page size is 20. The page size must not be greater than 100
     * @param {String} uuid UUID of the association whose committees are requested
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {module:api/SAMSAssociationsAPIApi~getSportsclubsForAssociationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SportsclubPage}
     */
    getSportsclubsForAssociation(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getSportsclubsForAssociation");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json'];
      let returnType = SportsclubPage;
      return this.apiClient.callApi(
        '/associations/{uuid}/sportsclubs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
