/**
 * SAMS REST API v2
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HalRepresentation from '../model/HalRepresentation';
import ResponseException from '../model/ResponseException';
import ResponseExceptionMessage from '../model/ResponseExceptionMessage';
import UserDetailsDto from '../model/UserDetailsDto';
import ValidationError from '../model/ValidationError';

/**
* SAMSUserAPI service.
* @module api/SAMSUserAPIApi
* @version 2.1
*/
export default class SAMSUserAPIApi {

    /**
    * Constructs a new SAMSUserAPIApi. 
    * @alias module:api/SAMSUserAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getCurrentUser operation.
     * @callback module:api/SAMSUserAPIApi~getCurrentUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UserDetailsDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves the user data for the current user identified by the mandatory JSON web token authorization header
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {module:api/SAMSUserAPIApi~getCurrentUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UserDetailsDto}
     */
    getCurrentUser(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = UserDetailsDto;
      return this.apiClient.callApi(
        '/user-details/current', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the userDetailsRootLinks operation.
     * @callback module:api/SAMSUserAPIApi~userDetailsRootLinksCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HalRepresentation} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Provides links to sub resources
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {module:api/SAMSUserAPIApi~userDetailsRootLinksCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HalRepresentation}
     */
    userDetailsRootLinks(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = HalRepresentation;
      return this.apiClient.callApi(
        '/user-details', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
