/**
 * SAMS REST API v2
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CompetitionMatchGroupDto from '../model/CompetitionMatchGroupDto';
import CompetitionMatchGroupPage from '../model/CompetitionMatchGroupPage';
import CompetitionMatchPage from '../model/CompetitionMatchPage';
import ResponseException from '../model/ResponseException';
import ResponseExceptionMessage from '../model/ResponseExceptionMessage';
import ValidationError from '../model/ValidationError';

/**
* SAMSMatchGroupsAPI service.
* @module api/SAMSMatchGroupsAPIApi
* @version 2.1
*/
export default class SAMSMatchGroupsAPIApi {

    /**
    * Constructs a new SAMSMatchGroupsAPIApi. 
    * @alias module:api/SAMSMatchGroupsAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAllMatchGroups operation.
     * @callback module:api/SAMSMatchGroupsAPIApi~getAllMatchGroupsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CompetitionMatchGroupPage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all available match groups as a paged list. The default page size is 20. The page size must not be greater than 100
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {String} [association] Filter for association using the given UUID. Defaults to no filtering.
     * @param {module:api/SAMSMatchGroupsAPIApi~getAllMatchGroupsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CompetitionMatchGroupPage}
     */
    getAllMatchGroups(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'association': opts['association']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = CompetitionMatchGroupPage;
      return this.apiClient.callApi(
        '/match-groups', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getMatchGroupByUuid operation.
     * @callback module:api/SAMSMatchGroupsAPIApi~getMatchGroupByUuidCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CompetitionMatchGroupDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a match group identified by the given UUID
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {module:api/SAMSMatchGroupsAPIApi~getMatchGroupByUuidCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CompetitionMatchGroupDto}
     */
    getMatchGroupByUuid(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getMatchGroupByUuid");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = CompetitionMatchGroupDto;
      return this.apiClient.callApi(
        '/match-groups/{uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getMatchesByMatchGroup operation.
     * @callback module:api/SAMSMatchGroupsAPIApi~getMatchesByMatchGroupCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CompetitionMatchPage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all matches corresponding to the match group identified by the given UUID
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {module:api/SAMSMatchGroupsAPIApi~getMatchesByMatchGroupCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CompetitionMatchPage}
     */
    getMatchesByMatchGroup(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getMatchesByMatchGroup");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = CompetitionMatchPage;
      return this.apiClient.callApi(
        '/match-groups/{uuid}/competition-matches', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
