/**
 * SAMS REST API v2
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CompetitionPage from '../model/CompetitionPage';
import LeagueHierarchyDto from '../model/LeagueHierarchyDto';
import LeagueHierarchyPage from '../model/LeagueHierarchyPage';
import LeaguePage from '../model/LeaguePage';
import ResponseException from '../model/ResponseException';
import ResponseExceptionMessage from '../model/ResponseExceptionMessage';
import SuperCompetitionPage from '../model/SuperCompetitionPage';
import ValidationError from '../model/ValidationError';

/**
* SAMSLeagueHierarchiesAPI service.
* @module api/SAMSLeagueHierarchiesAPIApi
* @version 2.1
*/
export default class SAMSLeagueHierarchiesAPIApi {

    /**
    * Constructs a new SAMSLeagueHierarchiesAPIApi. 
    * @alias module:api/SAMSLeagueHierarchiesAPIApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAllLeagueHierarchies operation.
     * @callback module:api/SAMSLeagueHierarchiesAPIApi~getAllLeagueHierarchiesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LeagueHierarchyPage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all available league hierarchy elements as a paged list.
     * The default page size is 20. The page size must not be greater than 100. The result list can be filtered for a particular season.
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {String} [forSeason] Filter for the season. UUID of the season to which the league hierarchy belongs.
     * @param {String} [association] Filter for association using the given UUID. Defaults to no filtering.
     * @param {module:api/SAMSLeagueHierarchiesAPIApi~getAllLeagueHierarchiesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LeagueHierarchyPage}
     */
    getAllLeagueHierarchies(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'for-season': opts['forSeason'],
        'association': opts['association']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = LeagueHierarchyPage;
      return this.apiClient.callApi(
        '/league-hierarchies', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCompetitionsByLeagueHierarchy operation.
     * @callback module:api/SAMSLeagueHierarchiesAPIApi~getCompetitionsByLeagueHierarchyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CompetitionPage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all competitions corresponding to the league hierarchy identified by the given UUID
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {module:api/SAMSLeagueHierarchiesAPIApi~getCompetitionsByLeagueHierarchyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CompetitionPage}
     */
    getCompetitionsByLeagueHierarchy(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getCompetitionsByLeagueHierarchy");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = CompetitionPage;
      return this.apiClient.callApi(
        '/league-hierarchies/{uuid}/competitions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getLeagueHierarchyByUuid operation.
     * @callback module:api/SAMSLeagueHierarchiesAPIApi~getLeagueHierarchyByUuidCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LeagueHierarchyDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a league hierarchy element identified by the given UUID
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {module:api/SAMSLeagueHierarchiesAPIApi~getLeagueHierarchyByUuidCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LeagueHierarchyDto}
     */
    getLeagueHierarchyByUuid(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getLeagueHierarchyByUuid");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = LeagueHierarchyDto;
      return this.apiClient.callApi(
        '/league-hierarchies/{uuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getLeaguesByLeagueHierarchy operation.
     * @callback module:api/SAMSLeagueHierarchiesAPIApi~getLeaguesByLeagueHierarchyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LeaguePage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all leagues corresponding to the league hierarchy identified by the given UUID
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {module:api/SAMSLeagueHierarchiesAPIApi~getLeaguesByLeagueHierarchyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LeaguePage}
     */
    getLeaguesByLeagueHierarchy(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getLeaguesByLeagueHierarchy");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = LeaguePage;
      return this.apiClient.callApi(
        '/league-hierarchies/{uuid}/leagues', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSuperCompetitionsByLeagueHierarchy operation.
     * @callback module:api/SAMSLeagueHierarchiesAPIApi~getSuperCompetitionsByLeagueHierarchyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SuperCompetitionPage} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all super competitions corresponding to the league hierarchy identified by the given UUID
     * @param {String} uuid 
     * @param {Object} opts Optional parameters
     * @param {String} [xApiKey] A SAMS API key with permission to access this API.
     * @param {Number} [page] Requested page number. Defaults to the first page (i.e. page number 0).
     * @param {Number} [size] Requested number of items per page. Defaults to 20. The maximum allowed value is 100
     * @param {module:api/SAMSLeagueHierarchiesAPIApi~getSuperCompetitionsByLeagueHierarchyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SuperCompetitionPage}
     */
    getSuperCompetitionsByLeagueHierarchy(uuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getSuperCompetitionsByLeagueHierarchy");
      }

      let pathParams = {
        'uuid': uuid
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
        'X-Api-Key': opts['xApiKey']
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/hal+json; charset=UTF-8'];
      let returnType = SuperCompetitionPage;
      return this.apiClient.callApi(
        '/league-hierarchies/{uuid}/super-competitions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
