<?php
/**
 * SAMSAssociationsAPIApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  SAMS\RestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SAMS REST API v2
 *
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SAMS\RestClient\Test\Api;

use \SAMS\RestClient\Configuration;
use \SAMS\RestClient\ApiException;
use \SAMS\RestClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SAMSAssociationsAPIApiTest Class Doc Comment
 *
 * @category Class
 * @package  SAMS\RestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SAMSAssociationsAPIApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAssociationByUuid
     *
     * Returns an association identified by the given UUID.
     *
     */
    public function testGetAssociationByUuid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAssociations
     *
     * Returns all available associations..
     *
     */
    public function testGetAssociations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCommitteesForAssociation
     *
     * Returns the list of committees..
     *
     */
    public function testGetCommitteesForAssociation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSportsclubsForAssociation
     *
     * .
     *
     */
    public function testGetSportsclubsForAssociation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
