<?php
/**
 * SAMSTeamsAPIApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  SAMS\RestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SAMS REST API v2
 *
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SAMS\RestClient\Test\Api;

use \SAMS\RestClient\Configuration;
use \SAMS\RestClient\ApiException;
use \SAMS\RestClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SAMSTeamsAPIApiTest Class Doc Comment
 *
 * @category Class
 * @package  SAMS\RestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SAMSTeamsAPIApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for constructor with default dependencies
     */
    public function testConstructorWithDefaults()
    {
        $api = new \SAMS\RestClient\Api\SAMSTeamsAPIApi();

        $this->assertInstanceOf(\SAMS\RestClient\Api\SAMSTeamsAPIApi::class, $api);
        $this->assertInstanceOf(Configuration::class, $api->getConfig());
        $this->assertEquals(0, $api->getHostIndex());
    }

    /**
     * Test case for constructor with custom dependencies
     */
    public function testConstructorWithCustomDependencies()
    {
        $mockClient = $this->createMock(\GuzzleHttp\ClientInterface::class);
        $config = new Configuration();
        $config->setHost('https://custom.api.host');
        $selector = new \SAMS\RestClient\HeaderSelector();

        $api = new \SAMS\RestClient\Api\SAMSTeamsAPIApi($mockClient, $config, $selector, 1);

        $this->assertEquals('https://custom.api.host', $api->getConfig()->getHost());
        $this->assertEquals(1, $api->getHostIndex());
    }

    /**
     * Test case for setHostIndex and getHostIndex
     */
    public function testSetAndGetHostIndex()
    {
        $api = new \SAMS\RestClient\Api\SAMSTeamsAPIApi();

        $api->setHostIndex(2);
        $this->assertEquals(2, $api->getHostIndex());
    }

    /**
     * Test case for getAllTeams request building
     */
    public function testGetAllTeamsRequest()
    {
        $api = new \SAMS\RestClient\Api\SAMSTeamsAPIApi();

        $request = $api->getAllTeamsRequest('test-api-key', 0, 20, 'assoc-uuid');

        $this->assertEquals('GET', $request->getMethod());
        $this->assertStringContainsString('/teams', (string) $request->getUri());
        $this->assertStringContainsString('page=0', (string) $request->getUri());
        $this->assertStringContainsString('size=20', (string) $request->getUri());
        $this->assertStringContainsString('association=assoc-uuid', (string) $request->getUri());
        $this->assertEquals('test-api-key', $request->getHeader('X-Api-Key')[0]);
    }

    /**
     * Test case for getAllTeams without optional parameters
     */
    public function testGetAllTeamsRequestWithoutOptionalParams()
    {
        $api = new \SAMS\RestClient\Api\SAMSTeamsAPIApi();

        $request = $api->getAllTeamsRequest();

        $this->assertEquals('GET', $request->getMethod());
        $this->assertStringContainsString('/teams', (string) $request->getUri());
        $this->assertStringNotContainsString('page=', (string) $request->getUri());
        $this->assertEmpty($request->getHeader('X-Api-Key'));
    }

    /**
     * Test case for getTeamByUuid with missing required parameter
     */
    public function testGetTeamByUuidWithMissingUuid()
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Missing the required parameter $uuid when calling getTeamByUuid');

        $api = new \SAMS\RestClient\Api\SAMSTeamsAPIApi();
        $api->getTeamByUuidRequest(null);
    }

    /**
     * Test case for getTeamByUuid request building
     */
    public function testGetTeamByUuidRequest()
    {
        $api = new \SAMS\RestClient\Api\SAMSTeamsAPIApi();
        $uuid = 'team-uuid-123';

        $request = $api->getTeamByUuidRequest($uuid, 'api-key-value');

        $this->assertEquals('GET', $request->getMethod());
        $this->assertStringContainsString('/teams/' . $uuid, (string) $request->getUri());
        $this->assertEquals('api-key-value', $request->getHeader('X-Api-Key')[0]);
    }

    /**
     * Test case for getTeamByUuid with empty array as uuid
     */
    public function testGetTeamByUuidWithEmptyArray()
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Missing the required parameter $uuid when calling getTeamByUuid');

        $api = new \SAMS\RestClient\Api\SAMSTeamsAPIApi();
        $api->getTeamByUuidRequest([]);
    }

    /**
     * Test case for content types constant
     */
    public function testContentTypesConstant()
    {
        $contentTypes = \SAMS\RestClient\Api\SAMSTeamsAPIApi::contentTypes;

        $this->assertIsArray($contentTypes);
        $this->assertArrayHasKey('getAllTeams', $contentTypes);
        $this->assertArrayHasKey('getTeamByUuid', $contentTypes);
        $this->assertEquals(['application/json'], $contentTypes['getAllTeams']);
        $this->assertEquals(['application/json'], $contentTypes['getTeamByUuid']);
    }

    /**
     * Test case to verify path parameter replacement
     */
    public function testPathParameterReplacement()
    {
        $api = new \SAMS\RestClient\Api\SAMSTeamsAPIApi();
        $specialUuid = 'uuid-with-special-chars-789';

        $request = $api->getTeamByUuidRequest($specialUuid);

        $this->assertStringContainsString($specialUuid, (string) $request->getUri());
        $this->assertStringNotContainsString('{uuid}', (string) $request->getUri());
    }

    /**
     * Test case for pagination parameters
     */
    public function testPaginationParameters()
    {
        $api = new \SAMS\RestClient\Api\SAMSTeamsAPIApi();

        $request = $api->getAllTeamsRequest(null, 4, 55);

        $this->assertStringContainsString('page=4', (string) $request->getUri());
        $this->assertStringContainsString('size=55', (string) $request->getUri());
    }
}