<?php
/**
 * SAMSLeaguesAPIApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  SAMS\RestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SAMS REST API v2
 *
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SAMS\RestClient\Test\Api;

use \SAMS\RestClient\Configuration;
use \SAMS\RestClient\ApiException;
use \SAMS\RestClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SAMSLeaguesAPIApiTest Class Doc Comment
 *
 * @category Class
 * @package  SAMS\RestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SAMSLeaguesAPIApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for constructor with default dependencies
     */
    public function testConstructorWithDefaults()
    {
        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();

        $this->assertInstanceOf(\SAMS\RestClient\Api\SAMSLeaguesAPIApi::class, $api);
        $this->assertInstanceOf(Configuration::class, $api->getConfig());
        $this->assertEquals(0, $api->getHostIndex());
    }

    /**
     * Test case for constructor with custom dependencies
     */
    public function testConstructorWithCustomDependencies()
    {
        $mockClient = $this->createMock(\GuzzleHttp\ClientInterface::class);
        $config = new Configuration();
        $config->setHost('https://custom.api.host');
        $selector = new \SAMS\RestClient\HeaderSelector();

        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi($mockClient, $config, $selector, 1);

        $this->assertEquals('https://custom.api.host', $api->getConfig()->getHost());
        $this->assertEquals(1, $api->getHostIndex());
    }

    /**
     * Test case for setHostIndex and getHostIndex
     */
    public function testSetAndGetHostIndex()
    {
        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();

        $api->setHostIndex(2);
        $this->assertEquals(2, $api->getHostIndex());
    }

    /**
     * Test case for getAllLeagues request building
     */
    public function testGetAllLeaguesRequest()
    {
        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();

        $request = $api->getAllLeaguesRequest('test-api-key', 0, 20, 'assoc-uuid', 'season-uuid');

        $this->assertEquals('GET', $request->getMethod());
        $this->assertStringContainsString('/leagues', (string) $request->getUri());
        $this->assertStringContainsString('page=0', (string) $request->getUri());
        $this->assertStringContainsString('size=20', (string) $request->getUri());
        $this->assertStringContainsString('association=assoc-uuid', (string) $request->getUri());
        $this->assertStringContainsString('season=season-uuid', (string) $request->getUri());
        $this->assertEquals('test-api-key', $request->getHeader('X-Api-Key')[0]);
    }

    /**
     * Test case for getAllLeagues without optional parameters
     */
    public function testGetAllLeaguesRequestWithoutOptionalParams()
    {
        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();

        $request = $api->getAllLeaguesRequest();

        $this->assertEquals('GET', $request->getMethod());
        $this->assertStringContainsString('/leagues', (string) $request->getUri());
        $this->assertStringNotContainsString('page=', (string) $request->getUri());
        $this->assertEmpty($request->getHeader('X-Api-Key'));
    }

    /**
     * Test case for getLeagueByUuid with missing required parameter
     */
    public function testGetLeagueByUuidWithMissingUuid()
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Missing the required parameter $uuid when calling getLeagueByUuid');

        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();
        $api->getLeagueByUuidRequest(null);
    }

    /**
     * Test case for getLeagueByUuid request building
     */
    public function testGetLeagueByUuidRequest()
    {
        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();
        $uuid = 'test-league-uuid-123';

        $request = $api->getLeagueByUuidRequest($uuid, 'api-key-value');

        $this->assertEquals('GET', $request->getMethod());
        $this->assertStringContainsString('/leagues/' . $uuid, (string) $request->getUri());
        $this->assertEquals('api-key-value', $request->getHeader('X-Api-Key')[0]);
    }

    /**
     * Test case for getLeagueByUuid with empty array as uuid
     */
    public function testGetLeagueByUuidWithEmptyArray()
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Missing the required parameter $uuid when calling getLeagueByUuid');

        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();
        $api->getLeagueByUuidRequest([]);
    }

    /**
     * Test case for getMatchDaysForLeague with missing required parameter
     */
    public function testGetMatchDaysForLeagueWithMissingUuid()
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Missing the required parameter $uuid when calling getMatchDaysForLeague');

        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();
        $api->getMatchDaysForLeagueRequest(null);
    }

    /**
     * Test case for getMatchDaysForLeague request building
     */
    public function testGetMatchDaysForLeagueRequest()
    {
        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();
        $uuid = 'league-uuid-456';

        $request = $api->getMatchDaysForLeagueRequest($uuid, 'key123', 1, 50);

        $this->assertEquals('GET', $request->getMethod());
        $this->assertStringContainsString('/leagues/' . $uuid . '/match-days', (string) $request->getUri());
        $this->assertStringContainsString('page=1', (string) $request->getUri());
        $this->assertStringContainsString('size=50', (string) $request->getUri());
        $this->assertEquals('key123', $request->getHeader('X-Api-Key')[0]);
    }

    /**
     * Test case for getRankingsForLeague with missing required parameter
     */
    public function testGetRankingsForLeagueWithMissingUuid()
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Missing the required parameter $uuid when calling getRankingsForLeague');

        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();
        $api->getRankingsForLeagueRequest(null);
    }

    /**
     * Test case for getRankingsForLeague request building
     */
    public function testGetRankingsForLeagueRequest()
    {
        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();
        $uuid = 'rankings-league-789';

        $request = $api->getRankingsForLeagueRequest($uuid, null, 2, 100);

        $this->assertEquals('GET', $request->getMethod());
        $this->assertStringContainsString('/leagues/' . $uuid . '/rankings', (string) $request->getUri());
        $this->assertStringContainsString('page=2', (string) $request->getUri());
        $this->assertStringContainsString('size=100', (string) $request->getUri());
    }

    /**
     * Test case for getTeamsForLeague with missing required parameter
     */
    public function testGetTeamsForLeagueWithMissingUuid()
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Missing the required parameter $uuid when calling getTeamsForLeague');

        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();
        $api->getTeamsForLeagueRequest(null);
    }

    /**
     * Test case for getTeamsForLeague request building
     */
    public function testGetTeamsForLeagueRequest()
    {
        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();
        $uuid = 'teams-league-999';

        $request = $api->getTeamsForLeagueRequest($uuid);

        $this->assertEquals('GET', $request->getMethod());
        $this->assertStringContainsString('/leagues/' . $uuid . '/teams', (string) $request->getUri());
    }

    /**
     * Test case for content types constant
     */
    public function testContentTypesConstant()
    {
        $contentTypes = \SAMS\RestClient\Api\SAMSLeaguesAPIApi::contentTypes;

        $this->assertIsArray($contentTypes);
        $this->assertArrayHasKey('getAllLeagues', $contentTypes);
        $this->assertArrayHasKey('getLeagueByUuid', $contentTypes);
        $this->assertArrayHasKey('getMatchDaysForLeague', $contentTypes);
        $this->assertArrayHasKey('getRankingsForLeague', $contentTypes);
        $this->assertArrayHasKey('getTeamsForLeague', $contentTypes);
        $this->assertEquals(['application/json'], $contentTypes['getAllLeagues']);
    }

    /**
     * Test case for getAllLeagues with custom content type
     */
    public function testGetAllLeaguesWithCustomContentType()
    {
        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();

        $request = $api->getAllLeaguesRequest(null, null, null, null, null, 'application/json');

        $this->assertNotNull($request);
        $this->assertEquals('GET', $request->getMethod());
    }

    /**
     * Test case to verify path parameter replacement
     */
    public function testPathParameterReplacement()
    {
        $api = new \SAMS\RestClient\Api\SAMSLeaguesAPIApi();
        $specialUuid = 'uuid-with-special-chars-123';

        $request = $api->getLeagueByUuidRequest($specialUuid);

        $this->assertStringContainsString($specialUuid, (string) $request->getUri());
        $this->assertStringNotContainsString('{uuid}', (string) $request->getUri());
    }
}