<?php
/**
 * RefereeTeamDtoTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SAMS\RestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SAMS REST API v2
 *
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SAMS\RestClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RefereeTeamDtoTest Class Doc Comment
 *
 * @category    Class
 * @description RefereeTeamDto
 * @package     SAMS\RestClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RefereeTeamDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RefereeTeamDto"
     */
    public function testRefereeTeamDto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "first_referee"
     */
    public function testPropertyFirstReferee()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "second_referee"
     */
    public function testPropertySecondReferee()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "third_referee"
     */
    public function testPropertyThirdReferee()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "challenge_referee"
     */
    public function testPropertyChallengeReferee()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
