<?php
/**
 * SAMSCompetitionsAPIApi
 * PHP version 8.1
 *
 * @category Class
 * @package  SAMS\RestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SAMS REST API v2
 *
 * The SAMS public REST API
 *
 * The version of the OpenAPI document: 2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SAMS\RestClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use SAMS\RestClient\ApiException;
use SAMS\RestClient\Configuration;
use SAMS\RestClient\FormDataProcessor;
use SAMS\RestClient\HeaderSelector;
use SAMS\RestClient\ObjectSerializer;

/**
 * SAMSCompetitionsAPIApi Class Doc Comment
 *
 * @category Class
 * @package  SAMS\RestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SAMSCompetitionsAPIApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getAllCompetitions' => [
            'application/json',
        ],
        'getCompetitionByUuid' => [
            'application/json',
        ],
        'getMatchGroupsForCompetition' => [
            'application/json',
        ],
        'getRankingsForCompetition' => [
            'application/json',
        ],
        'getTeamsForCompetition' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getAllCompetitions
     *
     * Returns all available competitions as a paged list.
     *
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string|null $association Filter for association using the given UUID. Defaults to no filtering. (optional)
     * @param  string|null $season Filter for season using the given UUID. Defaults to no filtering. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllCompetitions'] to see the possible values for this operation
     *
     * @throws \SAMS\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SAMS\RestClient\Model\ValidationError|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseException|\SAMS\RestClient\Model\CompetitionPage
     */
    public function getAllCompetitions($x_api_key = null, $page = null, $size = null, $association = null, $season = null, string $contentType = self::contentTypes['getAllCompetitions'][0])
    {
        list($response) = $this->getAllCompetitionsWithHttpInfo($x_api_key, $page, $size, $association, $season, $contentType);
        return $response;
    }

    /**
     * Operation getAllCompetitionsWithHttpInfo
     *
     * Returns all available competitions as a paged list.
     *
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string|null $association Filter for association using the given UUID. Defaults to no filtering. (optional)
     * @param  string|null $season Filter for season using the given UUID. Defaults to no filtering. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllCompetitions'] to see the possible values for this operation
     *
     * @throws \SAMS\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SAMS\RestClient\Model\ValidationError|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseException|\SAMS\RestClient\Model\CompetitionPage, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllCompetitionsWithHttpInfo($x_api_key = null, $page = null, $size = null, $association = null, $season = null, string $contentType = self::contentTypes['getAllCompetitions'][0])
    {
        $request = $this->getAllCompetitionsRequest($x_api_key, $page, $size, $association, $season, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 400:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ValidationError',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseException',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\CompetitionPage',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\SAMS\RestClient\Model\CompetitionPage',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseException',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\CompetitionPage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getAllCompetitionsAsync
     *
     * Returns all available competitions as a paged list.
     *
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string|null $association Filter for association using the given UUID. Defaults to no filtering. (optional)
     * @param  string|null $season Filter for season using the given UUID. Defaults to no filtering. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllCompetitions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllCompetitionsAsync($x_api_key = null, $page = null, $size = null, $association = null, $season = null, string $contentType = self::contentTypes['getAllCompetitions'][0])
    {
        return $this->getAllCompetitionsAsyncWithHttpInfo($x_api_key, $page, $size, $association, $season, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllCompetitionsAsyncWithHttpInfo
     *
     * Returns all available competitions as a paged list.
     *
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string|null $association Filter for association using the given UUID. Defaults to no filtering. (optional)
     * @param  string|null $season Filter for season using the given UUID. Defaults to no filtering. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllCompetitions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllCompetitionsAsyncWithHttpInfo($x_api_key = null, $page = null, $size = null, $association = null, $season = null, string $contentType = self::contentTypes['getAllCompetitions'][0])
    {
        $returnType = '\SAMS\RestClient\Model\CompetitionPage';
        $request = $this->getAllCompetitionsRequest($x_api_key, $page, $size, $association, $season, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllCompetitions'
     *
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string|null $association Filter for association using the given UUID. Defaults to no filtering. (optional)
     * @param  string|null $season Filter for season using the given UUID. Defaults to no filtering. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAllCompetitions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAllCompetitionsRequest($x_api_key = null, $page = null, $size = null, $association = null, $season = null, string $contentType = self::contentTypes['getAllCompetitions'][0])
    {







        $resourcePath = '/competitions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $association,
            'association', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $season,
            'season', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_key !== null) {
            $headerParams['X-Api-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/hal+json; charset=UTF-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCompetitionByUuid
     *
     * Returns a competition identified by the given UUID
     *
     * @param  string $uuid uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompetitionByUuid'] to see the possible values for this operation
     *
     * @throws \SAMS\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SAMS\RestClient\Model\ValidationError|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseException|\SAMS\RestClient\Model\CompetitionDto
     */
    public function getCompetitionByUuid($uuid, $x_api_key = null, string $contentType = self::contentTypes['getCompetitionByUuid'][0])
    {
        list($response) = $this->getCompetitionByUuidWithHttpInfo($uuid, $x_api_key, $contentType);
        return $response;
    }

    /**
     * Operation getCompetitionByUuidWithHttpInfo
     *
     * Returns a competition identified by the given UUID
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompetitionByUuid'] to see the possible values for this operation
     *
     * @throws \SAMS\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SAMS\RestClient\Model\ValidationError|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseException|\SAMS\RestClient\Model\CompetitionDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCompetitionByUuidWithHttpInfo($uuid, $x_api_key = null, string $contentType = self::contentTypes['getCompetitionByUuid'][0])
    {
        $request = $this->getCompetitionByUuidRequest($uuid, $x_api_key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 400:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ValidationError',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseException',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\CompetitionDto',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\SAMS\RestClient\Model\CompetitionDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseException',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\CompetitionDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getCompetitionByUuidAsync
     *
     * Returns a competition identified by the given UUID
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompetitionByUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompetitionByUuidAsync($uuid, $x_api_key = null, string $contentType = self::contentTypes['getCompetitionByUuid'][0])
    {
        return $this->getCompetitionByUuidAsyncWithHttpInfo($uuid, $x_api_key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCompetitionByUuidAsyncWithHttpInfo
     *
     * Returns a competition identified by the given UUID
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompetitionByUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompetitionByUuidAsyncWithHttpInfo($uuid, $x_api_key = null, string $contentType = self::contentTypes['getCompetitionByUuid'][0])
    {
        $returnType = '\SAMS\RestClient\Model\CompetitionDto';
        $request = $this->getCompetitionByUuidRequest($uuid, $x_api_key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCompetitionByUuid'
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getCompetitionByUuid'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getCompetitionByUuidRequest($uuid, $x_api_key = null, string $contentType = self::contentTypes['getCompetitionByUuid'][0])
    {

        // verify the required parameter 'uuid' is set
        if ($uuid === null || (is_array($uuid) && count($uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uuid when calling getCompetitionByUuid'
            );
        }



        $resourcePath = '/competitions/{uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_api_key !== null) {
            $headerParams['X-Api-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }

        // path params
        if ($uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'uuid' . '}',
                ObjectSerializer::toPathValue($uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/hal+json; charset=UTF-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMatchGroupsForCompetition
     *
     * Returns all match groups corresponding to the competition identified by the given UUID
     *
     * @param  string $uuid uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchGroupsForCompetition'] to see the possible values for this operation
     *
     * @throws \SAMS\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SAMS\RestClient\Model\ValidationError|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseException|\SAMS\RestClient\Model\CompetitionMatchGroupPage
     */
    public function getMatchGroupsForCompetition($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getMatchGroupsForCompetition'][0])
    {
        list($response) = $this->getMatchGroupsForCompetitionWithHttpInfo($uuid, $x_api_key, $page, $size, $contentType);
        return $response;
    }

    /**
     * Operation getMatchGroupsForCompetitionWithHttpInfo
     *
     * Returns all match groups corresponding to the competition identified by the given UUID
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchGroupsForCompetition'] to see the possible values for this operation
     *
     * @throws \SAMS\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SAMS\RestClient\Model\ValidationError|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseException|\SAMS\RestClient\Model\CompetitionMatchGroupPage, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMatchGroupsForCompetitionWithHttpInfo($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getMatchGroupsForCompetition'][0])
    {
        $request = $this->getMatchGroupsForCompetitionRequest($uuid, $x_api_key, $page, $size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 400:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ValidationError',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseException',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\CompetitionMatchGroupPage',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\SAMS\RestClient\Model\CompetitionMatchGroupPage',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseException',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\CompetitionMatchGroupPage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getMatchGroupsForCompetitionAsync
     *
     * Returns all match groups corresponding to the competition identified by the given UUID
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchGroupsForCompetition'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMatchGroupsForCompetitionAsync($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getMatchGroupsForCompetition'][0])
    {
        return $this->getMatchGroupsForCompetitionAsyncWithHttpInfo($uuid, $x_api_key, $page, $size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMatchGroupsForCompetitionAsyncWithHttpInfo
     *
     * Returns all match groups corresponding to the competition identified by the given UUID
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchGroupsForCompetition'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMatchGroupsForCompetitionAsyncWithHttpInfo($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getMatchGroupsForCompetition'][0])
    {
        $returnType = '\SAMS\RestClient\Model\CompetitionMatchGroupPage';
        $request = $this->getMatchGroupsForCompetitionRequest($uuid, $x_api_key, $page, $size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMatchGroupsForCompetition'
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMatchGroupsForCompetition'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getMatchGroupsForCompetitionRequest($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getMatchGroupsForCompetition'][0])
    {

        // verify the required parameter 'uuid' is set
        if ($uuid === null || (is_array($uuid) && count($uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uuid when calling getMatchGroupsForCompetition'
            );
        }





        $resourcePath = '/competitions/{uuid}/match-groups';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_key !== null) {
            $headerParams['X-Api-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }

        // path params
        if ($uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'uuid' . '}',
                ObjectSerializer::toPathValue($uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/hal+json; charset=UTF-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getRankingsForCompetition
     *
     * Returns the rankings of a competition identified by the given UUID.
     *
     * @param  string $uuid uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRankingsForCompetition'] to see the possible values for this operation
     *
     * @throws \SAMS\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SAMS\RestClient\Model\ValidationError|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseException|\SAMS\RestClient\Model\CompetitionRankingsResourcePage
     */
    public function getRankingsForCompetition($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getRankingsForCompetition'][0])
    {
        list($response) = $this->getRankingsForCompetitionWithHttpInfo($uuid, $x_api_key, $page, $size, $contentType);
        return $response;
    }

    /**
     * Operation getRankingsForCompetitionWithHttpInfo
     *
     * Returns the rankings of a competition identified by the given UUID.
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRankingsForCompetition'] to see the possible values for this operation
     *
     * @throws \SAMS\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SAMS\RestClient\Model\ValidationError|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseException|\SAMS\RestClient\Model\CompetitionRankingsResourcePage, HTTP status code, HTTP response headers (array of strings)
     */
    public function getRankingsForCompetitionWithHttpInfo($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getRankingsForCompetition'][0])
    {
        $request = $this->getRankingsForCompetitionRequest($uuid, $x_api_key, $page, $size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 400:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ValidationError',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseException',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\CompetitionRankingsResourcePage',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\SAMS\RestClient\Model\CompetitionRankingsResourcePage',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseException',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\CompetitionRankingsResourcePage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getRankingsForCompetitionAsync
     *
     * Returns the rankings of a competition identified by the given UUID.
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRankingsForCompetition'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRankingsForCompetitionAsync($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getRankingsForCompetition'][0])
    {
        return $this->getRankingsForCompetitionAsyncWithHttpInfo($uuid, $x_api_key, $page, $size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getRankingsForCompetitionAsyncWithHttpInfo
     *
     * Returns the rankings of a competition identified by the given UUID.
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRankingsForCompetition'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRankingsForCompetitionAsyncWithHttpInfo($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getRankingsForCompetition'][0])
    {
        $returnType = '\SAMS\RestClient\Model\CompetitionRankingsResourcePage';
        $request = $this->getRankingsForCompetitionRequest($uuid, $x_api_key, $page, $size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getRankingsForCompetition'
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRankingsForCompetition'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getRankingsForCompetitionRequest($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getRankingsForCompetition'][0])
    {

        // verify the required parameter 'uuid' is set
        if ($uuid === null || (is_array($uuid) && count($uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uuid when calling getRankingsForCompetition'
            );
        }





        $resourcePath = '/competitions/{uuid}/rankings';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_key !== null) {
            $headerParams['X-Api-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }

        // path params
        if ($uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'uuid' . '}',
                ObjectSerializer::toPathValue($uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/hal+json; charset=UTF-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getTeamsForCompetition
     *
     * Returns all teams of a competition identified by the given UUID as a paged list.
     *
     * @param  string $uuid uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTeamsForCompetition'] to see the possible values for this operation
     *
     * @throws \SAMS\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SAMS\RestClient\Model\ValidationError|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseException|\SAMS\RestClient\Model\TeamPage
     */
    public function getTeamsForCompetition($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getTeamsForCompetition'][0])
    {
        list($response) = $this->getTeamsForCompetitionWithHttpInfo($uuid, $x_api_key, $page, $size, $contentType);
        return $response;
    }

    /**
     * Operation getTeamsForCompetitionWithHttpInfo
     *
     * Returns all teams of a competition identified by the given UUID as a paged list.
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTeamsForCompetition'] to see the possible values for this operation
     *
     * @throws \SAMS\RestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SAMS\RestClient\Model\ValidationError|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseExceptionMessage|\SAMS\RestClient\Model\ResponseException|\SAMS\RestClient\Model\TeamPage, HTTP status code, HTTP response headers (array of strings)
     */
    public function getTeamsForCompetitionWithHttpInfo($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getTeamsForCompetition'][0])
    {
        $request = $this->getTeamsForCompetitionRequest($uuid, $x_api_key, $page, $size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 400:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ValidationError',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\ResponseException',
                        $request,
                        $response,
                    );
                case 200:
                    return $this->handleResponseWithDataType(
                        '\SAMS\RestClient\Model\TeamPage',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\SAMS\RestClient\Model\TeamPage',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseExceptionMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\ResponseException',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SAMS\RestClient\Model\TeamPage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getTeamsForCompetitionAsync
     *
     * Returns all teams of a competition identified by the given UUID as a paged list.
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTeamsForCompetition'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTeamsForCompetitionAsync($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getTeamsForCompetition'][0])
    {
        return $this->getTeamsForCompetitionAsyncWithHttpInfo($uuid, $x_api_key, $page, $size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getTeamsForCompetitionAsyncWithHttpInfo
     *
     * Returns all teams of a competition identified by the given UUID as a paged list.
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTeamsForCompetition'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getTeamsForCompetitionAsyncWithHttpInfo($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getTeamsForCompetition'][0])
    {
        $returnType = '\SAMS\RestClient\Model\TeamPage';
        $request = $this->getTeamsForCompetitionRequest($uuid, $x_api_key, $page, $size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getTeamsForCompetition'
     *
     * @param  string $uuid (required)
     * @param  string|null $x_api_key A SAMS API key with permission to access this API. (optional)
     * @param  int|null $page Requested page number. Defaults to the first page (i.e. page number 0). (optional)
     * @param  int|null $size Requested number of items per page. Defaults to 20. The maximum allowed value is 100 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getTeamsForCompetition'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getTeamsForCompetitionRequest($uuid, $x_api_key = null, $page = null, $size = null, string $contentType = self::contentTypes['getTeamsForCompetition'][0])
    {

        // verify the required parameter 'uuid' is set
        if ($uuid === null || (is_array($uuid) && count($uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uuid when calling getTeamsForCompetition'
            );
        }





        $resourcePath = '/competitions/{uuid}/teams';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_key !== null) {
            $headerParams['X-Api-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }

        // path params
        if ($uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'uuid' . '}',
                ObjectSerializer::toPathValue($uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/hal+json; charset=UTF-8', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
