name: Release ZIP-Version on GitHub

on:
    push:
      branches:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig phpunit.xml.dist composer.json composer.lock .wp-env.json /tests/*'
    
#    - name: Release zip file on GitHub
#      uses: ncipollo/release-action@v1.12.0
#      with:
#        artifacts: "release.zip"
#        token: ${{ secrets.GITHUB_TOKEN }}