name: Release ZIP-Version on GitHub

on:
    push:
      branches:
        - '**'

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build plugin
      run: |
        composer install --no-dev

    - name: Generate zip
      uses: 10up/action-wordpress-plugin-build-zip@stable
      env:
        SLUG: sams-plugin