name: Pipeline release

on:
    push:
      branches:
        - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Archive Pipeline Build
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: release-${{ github.run_id }}.zip
        exclusions: '*.git* /*node_modules/* .editorconfig phpunit.xml.dist composer.json composer.lock .wp-env.json /tests/*'
    
    - name: Upload release.zip
      uses: actions/upload-artifact@v4
      with:
        name: SAMS Plugin (zip file)
        path: release-${{ github.run_id }}.zip