name: Pipeline release

on:
    push:
      branches:
        - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer, phpunit
        extensions: simplexml

    - name: Install Composer dependencies
      run: composer install

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: "Install JS dependencies"
      run: npm install

    - name: Build Javascript
      run: npm run build
    
    - name: Manipulations for WordPress Plugin Release
    # 1. Replace generated echos by escaped output
      run: sed -i 's/echo \$err;/echo esc_html(\$err);/' lib/autoload.php
      
    - name: Prepare release folder
      run: mkdir releases/

    - name: Archive Pipeline Build
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: releases/snapshot-${{ github.run_id }}.zip
        exclusions: '*.git* /*node_modules/* .editorconfig phpunit.xml.dist composer.json composer.lock .wp-env.json /src/* /tests/* package.json package-lock.json /assets/*'
    
    - name: Upload Pipeline Release
      uses: actions/upload-artifact@v4
      with:
        name: Release ${{ github.run_id }} (SAMS Plugin)
        path: releases/snapshot-${{ github.run_id }}.zip
