name: Build, Test and Release WordPress Plugin

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
          extensions: simplexml

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node Modules
        run: npm install

  #test:
  #  runs-on: ubuntu-latest
#
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v4
#
  #    - name: Set up PHP
  #      uses: shivammathur/setup-php@v2
  #      with:
  #        php-version: '8.3'
  #        tools: composer, phpunit
  #        extensions: simplexml
#
  #    - name: Install Composer dependencies
  #      run: composer install
#
  #    - name: Install Node.js
  #      uses: actions/setup-node@v4
  #      with:
  #        node-version: '22'
#
  #    - name: Install wp-env
  #      run: npm install --global @wordpress/env
#
  #    - name: Start wp-env
  #      run: wp-env start
#
  #    - name: Run PHPUnit tests
  #      run: wp-env run tests-cli wp-content/plugins/sams-wordpress-plugin/lib/bin/phpunit wp-content/plugins/sams-wordpress-plugin
#
  #    - name: Stop wp-env
  #      run: wp-env stop
#

